### ISSUE TITLE
Add a command line option to verify configuration and exit

### ISSUE THREAD

**Issue by thedrow** [troglobit/smcroute#100]
It would be useful for our CI process to be able to verify the configuration of smcrouted.
Would you accept a PR that adds a command line option to smcrouted that says only verify configuration and exit?

**Comment by troglobit** [comment]
Sure, I've done something similar for troglobit/inadyn@fd3ef93, so that would be great.  How deep are you planning to go, verify interface names and group addresses, or just syntax?

**Comment by thedrow** [comment]
I thought about simply calling [`conf_parse()`](https://github.com/troglobit/smcroute/blob/master/src/conf.c#L283), so whatever it does is fine with me.
We can add more functionality later on right?

**Comment by thedrow** [comment]
Is `-C` acceptable as a command line option?

**Comment by thedrow** [comment]
Also acceptable.
`conf_parse()` is not part of the header right now. Are you planning to change the signature or can we make it "public"?

**Comment by troglobit** [comment]
Go ahead and change what you need. Personally I might've refactored `conf_read()` a bit instead, e.g. moved the `access()` check and error handling to `conf_parse()`, but it's up to you :-)

**Comment by troglobit** [comment]
Any progress on this?

**Comment by thedrow** [comment]
I haven't had the chance to reach this yet. You'll see a PR once I will.
I hope it will be soon.

**Comment by troglobit** [comment]
OK, just checking :)

**Comment by troglobit** [comment]
@thedrow Hi again. I just added a very simple `.conf` verifyer for the upcoming v2.5 release.  I'll see what I can do about making it a bit more strict; error (return 1) on malformed directives and warn on unknown directives.
