### ISSUE TITLE
Wrong type for field ifindex in struct iface

### ISSUE THREAD

**Issue by rene-d** [troglobit/smcroute#109]
In Linux kernel, the ifindex is stored into a int variable (aka. 4 bytes). And can take values greater than 65535 (I don't know since which version...).

The ifindex field in the structure iface (ifvc.h) is a u_short, and big indices cannot fit. It occurs especially on servers running tests that create/destroy bridges and virtual interfaces.

smcroute exits with "Failed adding VIF for iface ..." message : it tries to set an option on a inexistant interface (2000 instead of 67536 for example).

**Comment by rene-d** [comment]
Nota: I haven't tried to change the type and recompile...

**Comment by troglobit** [comment]
The most obvious fix, as mentioned in #71, is to simply change from `u_short` to `int`. However, I just noticed we use [if_nametoindex(3)](https://linux.die.net/man/3/if_nametoindex), which returns an `unsigned int` ... the kernel itself seems to use `int` for every relevant internal struct, so I propose changing to `int`.

**Comment by troglobit** [comment]
I've looked into this a bit further now and I don't see any other code, than the `struct iface` ifindex, that need to be changed.

I'm pushing a fix for that now, which will cause GitHub to automatically close this issue. Please, if you can @rene-d, test the fix.  If it doesn't work we'll reopen this issue again.  Thanks!

**Comment by rene-d** [comment]
Ok thanks! I will test tomorrow.

**Comment by rene-d** [comment]
Yes! the fix (type changed from u_short to int) solves the problem of interface indices greater than 2^16.

**Comment by troglobit** [comment]
@rene-d Awesome, thank you for getting back on this! :tada: :smiley:

**Comment by rene-d** [comment]
Thank you for having dealt with my issue so fast ;-)

I have look for ifindex in the Linux kernel: sometimes it's typed u32, sometimes int. In net/core/dev.c line ~8034 in function dev_new_index(), ifindex is a strictly positive int (aka  between 1 and 2^31-1).
