### ISSUE TITLE
Send SIGHUP or exec smcroutectl restart will terminate the smcrouted

### ISSUE THREAD

**Issue by weyou** [troglobit/smcroute#110]
1. Run the "smcrouted -N"
2. Send *SIGHUP* with *killall -SIGHUP smcrouted*
or 
Execute command: smcroutectl restart
3. The process of smcrouted exists unexpectedly.

**Comment by troglobit** [comment]
What version of SMCRoute are you getting this with?  I just tried the latest from the master branch (yet to be released v2.4.2) and cannot reproduce.

**Comment by troglobit** [comment]
@weyou PING?

**Comment by troglobit** [comment]
@weyou I'm sorry but I have not heard back from you on this matter, so I'm closing this issue since I cannot reproduce it.   If you have more information, e.g. SMCRoute version you used or anything that can help reproduce the issue, please do not hesitate to let me know and I'll reopen this.
