### ISSUE TITLE
smcroutectl fails if smcrouted daemon is not yet ready

### ISSUE THREAD

**Issue by igregr** [troglobit/smcroute#111]
Hello,
I have a script that starts the daemon when a user adds a multicast route via a custom CLI that calls smcroutectl in background. With the default smcroute systemd unit, I occasionally  receive the following error message as the daemon is not yet ready when the script issues `smcroutectl add ...` command:

```
smcroutectl: Cannot find IPC socket /var/run/smcroute.sock
smcroutectl: Daemon may be running with another -I NAME
```
It seems to me, that if systemd unit file use Type=forking, it should solve the problem as systemd should wait until smcrouted returns from fork. Is there a reason why the systemd unit file uses Type=simple? Could it be changed in some future release or is there any better way how to handle this kind of problems?

**Comment by troglobit** [comment]
There would still be a window between SMCRoute has forked but before it has created the domain socket.  I suggest you add some check for the SMCRoute PID file before calling smcroutectl.

**Comment by bombadil** [comment]
To get rid of that window smcroute could make use of sd_notify() and use the notify type in its systemd unit file.

**Comment by igregr** [comment]
Thanks for your suggestions. I will add some check for the PID file as it's pretty straightforward and will test the sd_notify() as it looks as a cleaner approach.

**Comment by troglobit** [comment]
Note, in commit 0b6cd0e4b support for `sd_notify()` was added. For more information, see #122.
