### ISSUE TITLE
source multicasts

### ISSUE THREAD

**Issue by mjoseph2019** [troglobit/smcroute#113]
Hello,
I'm using 2.4.0 and I am having some issues.
Maybe I'm misconfiguring or misunderstanding how this feature works but I can't get my servers using smcroute to join specific groups from specific sources.

My configuration is the following;

mgroup from eth0 group 225.x.y.z source 100.102.x.y

Now when I restart smcroute the daemon states everything is fine but when I do the "smcroutectl show" command I see multicast group I'm expecting but I also see all of the other ones that I do not want to see.

Am I not understanding correctly that if I specify a source IP that it should only join that group that is listed?

Thanks.

**Comment by troglobit** [comment]
To see groups joined by smcrouted you need to type `smcroutectl show group`, otherwise it displays multicast routes, both active and blocked.

**Comment by mjoseph2019** [comment]
Good to know, thank you for the quick response troglobit.
I didn't see any documentation on your site to see what multicast groups are joined but I could have just missed it.

**Comment by troglobit** [comment]
It should be in the man page ... that's the main source of information for SMCRoute.

Maybe we can close this issue then?

**Comment by mjoseph2019** [comment]
Yup this can be closed.
Thanks again for the information.

**Comment by troglobit** [comment]
np
