### ISSUE TITLE
Source address translation and smcroute

### ISSUE THREAD

**Issue by tewarid** [troglobit/smcroute#12]
Hi. I've built a basic Linux router that performs NAT using iptables. I'm using smcroute to do static routing of multicast packets. After initiating smcroute, source address translation in multicast packets seems to kick in after tens of seconds to minutes. I'm wondering if something could be wrong with my setup. What influence does smcroute have on NAT, if any? More details towards the end of http://delog.wordpress.com/2014/11/26/enable-ip-multicast-routing-in-linux-kernel/. Thank you.

**Comment by troglobit** [comment]
This doesn't look like a bug in SMCRoute.  Can we close it?

**Comment by tewarid** [comment]
I'm fine with closing the issue.

**Comment by troglobit** [comment]
Thanks! :)

**Comment by ncoghlan** [comment]
@tewarid I know this ticket was closed a long time ago, but did you ever track down the configuration problem?

I am seeing a very similar issue with routing through a network namespace, where just after the namespace is set up, everything looks fine (the trunk interface is a VLAN connection on a physical link, the peer interface is a virtual connection back to the hosts root network namespace):

```
$ sudo ip mroute show
(10.17.1.51, 239.255.60.60)      Iif: v-trunk11  Oifs: v-peer11
(10.18.0.112, 239.255.60.60)     Iif: v-trunk11  Oifs: v-peer11
(10.18.0.101, 239.255.60.60)     Iif: v-trunk11  Oifs: v-peer11
(10.17.11.1, 239.255.255.253)    Iif: v-peer11   Oifs: v-trunk11
(10.17.11.1, 239.255.60.60)      Iif: v-peer11   Oifs: v-trunk11
```

But after some triggering event (it isn't clear what), the mroute table gets extra entries mapping NATted addresses in addition to unNATted ones. The spurious entries look like:

```
(10.18.11.112, 239.255.60.60)     Iif: v-trunk11  Oifs: v-peer11
(10.18.11.101, 239.255.60.60)     Iif: v-trunk11  Oifs: v-peer11
```

**Comment by tewarid** [comment]
@ncoghlan No, I wasn't able to figure out the cause at the time, and haven't looked into it since then.

**Comment by ncoghlan** [comment]
Thanks. I'll keep digging, and follow up on https://serverfault.com/questions/1007003/iptables-snat-not-applied-in-multicast-routed-traffic if I find out anything useful.

**Comment by Ignassas15** [comment]
@ncoghlan Hi, were you able find anything out? The question you linked to was since deleted and wayback machine only has a snapshot when it was created.
