### ISSUE TITLE
Please update the old version in Entware for ARMv7

### ISSUE THREAD

**Issue by smcgrath12** [troglobit/smcroute#123]
Hello, I am not sure what the steps are to update the “ipk” file in Entware for SMCRoute. My router is ASUS RT-AC68. The current ipk file at https://bin.entware.net/armv7sf-k3.2/ for SMCRoute is for version 2.0.0, which is almost 5 years old.

I submitted a request to Entware to update to version 2.4.4, but I got a reply of:

“This package came from upstream with no changes.

Please, ask maintainers to update it. The new version will arrive here during next sync.”

I am not sure if this means that you have to “push” the new version to Entware.. Any help is highly appreciated. Thank you.

**Comment by troglobit** [comment]
Hi, great to hear SMCRoute being used in so many places! However, we (I) am not the maintainer of the package in Entware. 

From the traces you've left on GitHub it seems you've learned this and instead filed an issue with OpenWrt. 

I'm closing this now.

**Comment by smcgrath12** [comment]
Yes, I was asked to send my request to OpenWRT. Sorry for the double post, wasn’t sure how to do it. Thank you for your work in SMCRoute.
