### ISSUE TITLE
smcroute reports no multicast support on openwrt router

### ISSUE THREAD

**Issue by verslyap** [troglobit/smcroute#128]
I tried smcroute on my openwrt router and when I started it, it left an entry in my log file about the kernel not supporting multicast routing.  Another multicast routing daemon I had used worked okay, so I don't think this can be accurate.

**Comment by troglobit** [comment]
What version of SMCRoute did you try?  This is the upstream SMCRoute project and we only release source code, no pre-built packages for any UNIX or Linux distribution (desktop or embedded).  Very often we get bug reports here about badly packaged and old versions of SMCRoute, which we sadly cannot do much about, other than regrettably redirect the reporter to the downstream project.

Now, there are actually more than one log message that signals missing kernel support. So a bit more information about the actual error would also be very useful. I'm also curious about what other multicast routing daemon you've tried (I maintain several, so aligning behavior between them is important to me :)

**Comment by verslyap** [comment]
I'll have to get some of the output for you this weekend.  But I built it from openwrt's github repository (along with openwrt's latest source with multicast support explicitly enabled).  it looks like that's 2.4.4.

The other daemon I'm using is multicast-relay.py.  I'm actually having a bit of trouble with that one as well, but it works here-and-there.

**Comment by troglobit** [comment]
The multicast-relay.py is a user space relay, meaning it does all packet forwarding in user space (by joining *all* multicast groups on one socket on one interface and using send() to a socket on another interface).

SMCRoute, pimd, pim6sd, mrouted, and other similar multicast routing daemons, use the kernel multicast routing table.  For this functionality to be unlocked the kernel must be compiled with `CONFIG_IP_MULTICAST, CONFIG_IP_MROUTE, CONFIG_IP_MROUTE_COMMON and CONFIG_IP_PIMSM_V2`. Hope this helps!

**Comment by verslyap** [comment]
I missed enabling CONFIG_IP_PIMSM_V2 on the custom build of openwrt I am using.  Issue resolved, thank you for being so helpful/responsive.

For anybody else finding this via google, I also had to build ip-tiny from source and manually install it on my openwrt router.  It's not in the repos for whatever weird reason.

**Comment by troglobit** [comment]
Glad to hear you found the problem :)
Closing
