### ISSUE TITLE
Add support for DHCP client interfaces

### ISSUE THREAD

**Issue by troglobit** [troglobit/smcroute#13]
Some users want to run smcroute on DHCP client interfaces.

Such interfaces may not yet have a acquired a DHCP lease and will currently be filtered out by the `iface_init()` function. 

A valid IP seems to be required when registering new VIF's in the kernel, this needs to be verified of course.  If it turns out that an IP is required we need to add support for handling interfaces that may lose their IP (remove VIF) or suddenly receive a lease (add VIF) dynamically. 

Affected multicast routes must be removed and added accordingly as well, of course.

This is Westermo WeOS issue #11865.

**Comment by bombadil** [comment]
Seems like a complex task. Wouldn't it be sufficient to hook into already available DHCP client hooks to restart smcroute as soon as something relevant happens to the interface address?

**Comment by troglobit** [comment]
@bombadil Yeah, we talked about this today at work. Problem is that if you do that existing routes on other (possibly also DHCP) interfaces will be affected. For our use-cases that's not OK.

It's not a highly prioritized issue at the moment, we will advice the customer to use a fake/dummy secondary IP address on DHCP interfaces as a work-around.  But I'll likely have a look at this later on.

The spin-off from such a refactor could also help us support dynamic interfaces, e.g., USB based ethernet/wifi, or more likely PPP and VLAN interfaces.

**Comment by troglobit** [comment]
Awesome, Linux has a `VIFF_USE_IFINDEX` flag you can pass to the kernel when registering VIFs. This means it is possible, at least on Linux, to support dynamic address on interfaces.

I will add this for v2.1 and add a note in the documentation that it's not support on *BSD.

Also, support for dynamic interfaces, e.g. USB Ethernet dongles being plugged in at runtime, will not be supported with this feature addition.
