### ISSUE TITLE
Dynamic IPv6 routes are not flushed

### ISSUE THREAD

**Issue by hubertmis** [troglobit/smcroute#130]
Wildcard source for IPv6 routing is supported now, but the cache is getting bigger and bigger with each added source address. It seems that flushing of IPv6 dynamic routes is missing.
@troglobit, do you plan to implement it during the refactoring you mentioned in #129?

**Comment by troglobit** [comment]
It's not in my immediate plan, no. Should be fairly easy to add an `mroute6_dyn_expire()` though ... so you're most welcome to add it.

**Comment by troglobit** [comment]
Fixed in 97ee681.  The IPv4 and IPv6 code now share the same code path.  Test available in `test/expire.sh`.
