### ISSUE TITLE
Failed Join Group - Address already in use

### ISSUE THREAD

**Issue by thomaslees** [troglobit/smcroute#131]
I followed the tutorial at 
https://github.com/jimpick/mininet-multicast-routing. 
A multcast network topology is created with mininet and smcroute
Everything seems to be fine 
When I issue the command at one of the hosts (h1)
/opt/smcroute/sbin/smcroutectl -I smcroute-h1 join h1-eth0 239.0.0.1
I get the following error from smcroutectl
Failed Join Group - Address already in use

**Comment by troglobit** [comment]
I'm not familiar with his setup, but that error message is returned by the kernel if you've already joined that group on the given interface.   So maybe there's a duplicate line somewhere?  Either way, it doesn't sound like an issue with SMCRoute.

You can see the currently joined groups, for instance `smcroute-h1`, using:

    /opt/smcroute/sbin/smcroutectl -I smcroute-h1 show groups

**Comment by thomaslees** [comment]
Thank you Joachim for your quick response. When I issue the command
I see multiple entries for the same IP and same Interface.
I could resolve the issue by leaving the group and joining again. Thanks once again

**Comment by troglobit** [comment]
No problem, good luck with your project!

**Comment by cliff101532** [comment]
I've followed the same tutorial. I got some problems.
When I try to ping the group address of 239.0.0.1 from h2(172.16.0.100) it is not reachable. I used wireshark to observe h1-eth0 interface and I can't receive any package.
I'm trying to do is that I want to ping a multicast group address and I wish the group member like h1 can get the multicast package. I'm wondering is there any mistakes in this topo or settings.

**Comment by troglobit** [comment]
@cliff101532 I've not tested mininet myself, but the file [multicastdemo.py](https://github.com/jimpick/mininet-multicast-routing/blob/master/multicastdemo.py) in the project use the wrong syntax to `smcroutectl`.  Check the documentation and you should be able to update the syntax.
