### ISSUE TITLE
What will happen if I add a route without joining a group

### ISSUE THREAD

**Issue by ma366** [troglobit/smcroute#134]

**Comment by troglobit** [comment]
If it's a (S,G) route, as opposed to a (*,G) route which involves handling from SMCRoute at runtime.  Then a route will be added in the kernel, and when matching multicast ingresses the inbound interface it will be routed to the outbound interface(s) listed in the route.

A multicast join is mostly only useful for LANs where switches with IGMP snooping exist and you cannot configure a static multicast router port on.
