### ISSUE TITLE
Different MC groups

### ISSUE THREAD

**Issue by manetix** [troglobit/smcroute#136]
Hi, is there any way to subscribe to a inbound MC group and select a different MC group for outbound?

Thanks.

**Comment by troglobit** [comment]
No, SMCRoute only routes multicast.  If you're using Linux I'd suggest looking at iptables or tc.

**Comment by manetix** [comment]
Nice, thanks!

**Comment by manetix** [comment]
It is not clear for me how to use multicast NAT between two network interfaces using iptables. Could you please give me an example?
Thanks in advance.

**Comment by troglobit** [comment]
Iptables isn't my strong suite, we have people at work that know that stuff much better than I do.  But I guess you have two options, some actions can be done on PREROUTING and some on POSTROUTING, so read up on DNAT and/or NETMAP.
