### ISSUE TITLE
Can't build according to new instructions

### ISSUE THREAD

**Issue by idosch** [troglobit/smcroute#141]
Hi,

Commit 068b1ec72573 ("Don't guess path for /var/run, use configure --runstatedir instead") changed the build instructions to:

```
# ./configure --prefix=/usr --sysconfdir=/etc --runstatedir=/var/run
```

However, it produces the following error on my system (Fedora 29):

```
# ./configure --prefix=/usr --sysconfdir=/etc --runstatedir=/var/run
configure: error: unrecognized option: `--runstatedir=/var/run'
Try `./configure --help' for more information
```

Previous versions worked on the same system with:

```
# ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
```

Thanks in advance, Ido.

**Comment by troglobit** [comment]
Hi,

yeah I recently learned that runstatedir is an unofficial feature that many distros, but not all, have backported from the as-of-yet unreleased autoconf 2.70 to their 2.69 version (released in 2012!).  It should still work with `--localstatedir=/var` though.  Could you please tell me if that works, or if a configure script generated on Fedora is completely broken?

 /J

**Comment by idosch** [comment]
> Hi,
> 
> yeah I recently learned that runstatedir is an unofficial feature that many distros, but not all, have backported from the as-of-yet unreleased autoconf 2.70 to their 2.69 version (released in 2012!). It should still work with `--localstatedir=/var` though. Could you please tell me if that works, or if a configure script generated on Fedora is completely broken?

Thanks for the quick reply. It does not seem to work with `--localstatedir=/var`. I get:

```
# smcroutectl -I selftests add swp2 198.51.100.2 225.1.2.3 swp3 swp5
# smcroutectl: Cannot find IPC socket @runstatedir@/selftests.sock
# smcroutectl: Daemon may be running with another -I NAME
```

When the daemon was started with:

```
# smcrouted -N -I selftests -f /tmp/tmp.jEUMy4k5uR/selftests.conf -P /tmp/tmp.jEUMy4k5uR/selftests.pid
```

FWIW, this is the summary after running `./configure` with `--localstatedir=/var`:

```
------------------ Summary ------------------ 

 SMCRoute version 2.5.0-beta1 

  Prefix.........: /usr 

  Sysconfdir.....: /etc 

  Runstatedir....: 

  C Compiler.....: gcc -g -O2 

 

 Optional features: 

  IPv6...........: yes 

  Client IPC.....: yes 

  Config file....: yes 

  MRDISC RFC4286.: no 

  libcap.........: yes 

  systemd........: /usr/lib/systemd/system 

  libsystemd.....: yes 

 

------------- Compiler version -------------- 

gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2) 

Copyright (C) 2018 Free Software Foundation, Inc. 

This is free software; see the source for copying conditions.  There is NO 

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

--------------------------------------------- 
```

**Comment by troglobit** [comment]
I hope 140ad02 fixes this for you.  This is the same workaround I've tried in the sysklogd and inadyn projects as well.

**Comment by idosch** [comment]
> I hope [140ad02](https://github.com/troglobit/smcroute/commit/140ad02b104f9bbddcb0f9e6addc966430de26e5) fixes this for you, if not please let me know and we can reopen the issue. This is the same workaround I've tried in the sysklogd and inadyn projects as well.

Yes, it fixes the issue. Thank you!

**Comment by troglobit** [comment]
Awesome, thank you for taking the time to verify! 😃
