### ISSUE TITLE
IPv6 add without source

### ISSUE THREAD

**Issue by Radvendii** [troglobit/smcroute#144]
Running `smcroutectl add eth1.10 ff08::10 eth1.232` results in the weird error message`smcroutectl: Invalid IPv6 group address`. 

Eventually I figured out that this was because it's interpretting `ff08::10` as the source address and `eth1.232` as the group address, which is indeed invalid.

This is contrary to the help text, however, which says that the source address is optional (which it is when using ipv4)

There are a few ways I can see fixing this (not mutually exclusive):
- change the help text to specify the usage with IPv6
- parsing the arguments like we do for ipv4, and outputting a helpful error message when the source is not included (e.g. "for IPv6 routes, source is required")
- allowing (*,G) routes for IPv6 (I know this is already being discussed in #31)

Thoughts? Is there a better solution?

**Comment by troglobit** [comment]
What version of SMCRoute are you using, master?  Iirc the latest release should be documented better.

The master branch is currently under development/refactor and I'm planning to make the IPv6 code work more like the IPv4 does.  Unfortunately I've been quite busy lately with lots of other stuff (apart from life, work, etc :)

**Comment by Radvendii** [comment]
Oh. I was indeed on master. Thanks, and no worries. I know how life gets. Thanks for making and maintaining this tool!

**Comment by troglobit** [comment]
Thank you, for taking the time to report this!  I think I needed a reminder to pick up the pace :)
