### ISSUE TITLE
Bad udp checksum on multicast answer

### ISSUE THREAD

**Issue by stieler-it** [troglobit/smcroute#147]
I am trying to receive SSDP messages in a network isolated Docker container and respond to it.

/etc/smcroute.conf:
```
mgroup from eth0 group 239.255.255.250
mroute from eth0 group 239.255.255.250 to docker0
mroute from docker0 group 239.255.255.250 to eth0
```

First line is join to the group (my router is not forwarding packets otherwise). With second line I achieved to see the SSDP packets inside Docker containers. Now the problem is that my application needs to respond back, which is why I added the third line.

Now my problems / questions:

The response is not accepted (could have different reasons) but I noticed it shows up in tcpdump on the host like this:

```
00:21:13.939215 IP (tos 0x0, ttl 3, id 10759, offset 0, flags [DF], proto UDP (17), length 317)
    localhost.1900 > 239.255.255.250.1900: [bad udp cksum 0x9d4b -> 0xf00d!] UDP, length 289
```

1. The Docker container is network isolated and thus has a different IP than the host. If a SSDP packet is created inside the container, it can only use it's internal IP as source address. Does smcroute apply NAT / address exchange before sending it on `eth0` ? Isn't `localhost` wrong in both cases?
2. tcpdump shows "bad udp cksum". Is this maybe because smcroute DID change the source address which makes the UDP checksum invalid which was built assuming another source address in it's pseudo header?
3. Any ideas how to solve this? I know I could start the Docker container without network isolation which seems to be the only available solution out there. But it feels this is already close...

**Comment by troglobit** [comment]
Hi, first of all: SSDP is not supposed to be routed, it is link-local only.

Now, SMCRoute only does join (like you discovered you need for the sender network to forward the traffic to you) and create multicast routes in the kernel multicast routing table.  SMCRoute is not involved in the actual forwarding of packets, including any form of NAT.  That is entirely the kernel's business (and the operator's).

Personally I'd put the docker container in a shared network setup, i.e. bridged, that is what I recommend most people trying to route SSDP (or mDNS, or other link-local traffic).  I cannot really support you any further than that.

**Comment by stieler-it** [comment]
Thanks for the information.

Not sure about your recommendation, docker0 is called bridge in Docker terms but it only bridges between containers. But I know "bridge" networking from VirtualBox where basically the VM gets it's own IP address in the host's network. Never heard that would be possible in Docker and it would not solve my problem as I would lose communication between containers.

But I get that this is totally out of scope of SMCRoute and I also realized that NAT is done by the kernel, not by SMCRoute, after I posted the question. Sorry for that, I thought maybe it's just a setting I am missing. Closing the ticket, thanks again.

**Comment by troglobit** [comment]
Maybe you can find some sort of DLNA/SSDP proxy or some sort. Because a proxy would not care about the IP TTL field, while routing SSDP may cause loss of traffic due to too low TTL. Just watch out :)

Good luck!

**Comment by stieler-it** [comment]
Thanks, TTL actually wasn't a problem but maybe because I followed the hints and used this:
`iptables -t mangle -A PREROUTING -d 239.255.255.250 -j TTL --ttl-inc 1`

**Comment by troglobit** [comment]
Yup, that ugly monster of a hack fixed it ;)
