### ISSUE TITLE
Dynamically add multicast routes 

### ISSUE THREAD

**Issue by Eunice0101** [troglobit/smcroute#148]
I configure smcroute.conf  only with following a command, it doesn't work.
mroute from eth0 group 225.0.0.0/24 to eth1 

Can't eth0 send multicast packets to eth1 from ANY source and ANY multicast address?

**Comment by troglobit** [comment]
Provided you use the `master` branch of SMCRoute, from at least GIT hash 8ff3014, and you receive multicast in the range 225.0.0.0-225.0.0.255 on `eth0`, then yes it should work.   This support will be included in the next official release, which is not yet ready.

Your specific question, however, applies to *any* multicast address and that's not what your `smcroute.conf` states.

**Comment by Eunice0101** [comment]
After update smcroute version 2.4.4, and configure smcroute.conf included the following three commands.
phyint eth0 enable
phyint eth1 enable
mroute from eth0 group 224.0.0.0/4 to eth1 

then eth1 can get any multicast packets from eth0, it works as I expected.
Thanks for help a lot.

**Comment by troglobit** [comment]
So you were running an older version first?  OK, so we can close this issue now then?

**Comment by Eunice0101** [comment]
Sure! thanks!
