### ISSUE TITLE
Multicast Routing to a GRE tunnel

### ISSUE THREAD

**Issue by MPEIXOTO** [troglobit/smcroute#15]
Hello,

I am using smcroute "SMCRoute version 2.0.0 build 141102" on a server with Ubuntu 15.
To route several multicast from one interface(em2) to a GRE tunnel interface(gre00).

But when i try to setup the routing rule I get the error below:

    $ sudo smcroute -a em2 192.168.113.100 239.255.1.1 gre00
    Daemon error: Invalid output interface

I can route it to  a physical interface:

    $ sudo smcroute -a em2 192.168.113.100 239.255.1.1 em4
    $ip mroute
    (192.168.113.100, 239.255.1.1)   Iif: em2        Oifs: em4 

But not to the GRE interface.  Does SMCRoute permits to do this configuration to an GRE interface?

Thanks in advance.

Manuel

**Comment by troglobit** [comment]
This may very well be related to issue #13.  

Does the GRE interface exist and has an IP address when the `smcroute` daemon starts?  Currently there is a limitation to smcroute in that it cannot handle dynamic interfaces.

**Comment by bombadil** [comment]
You can lookup the supported interfaces of your system in the file 
/proc/net/ip_mr_vif.

Another idea: Is the GRE tunnel interface created after smcroute was 
started? I don't know if smcroute is already able to detect the addition 
of interface at runtime. Maybe you need to restart smcroute to re-build 
the list of interfaces.

**Comment by MPEIXOTO** [comment]
Hi All,

First thanks for the prompt reply!

I do the following configurations steps:

1) 
sudo ip tunnel add gre00 remote REMOTE_SERVER local 192.168.3.213 ttl 255 dev em4
sudo ip link set gre00 up
sudo ip link set gre00 multicast on  
sudo ip addr add 10.10.10.1/30 broadcast 10.10.10.3 dev gre00

sudo echo 1 > /proc/sys/net/ipv4/ip_forward
sudo echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter
net.ipv4.conf.all.mc_forwarding = 1


2) I see that the interface is up, and I can ping the other endpoint of the GRE tunnel:

$ ifconfig
em2       Link encap:Ethernet  HWaddr f8:bc:12:3b:47:3d  
          inet addr:192.168.113.213  Bcast:192.168.113.255  Mask:255.255.255.0
          inet6 addr: fe80::fabc:12ff:fe3b:473d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:35839065 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:48812806530 (48.8 GB)  TX bytes:680 (680.0 B)
          Interrupt:49 

em4       Link encap:Ethernet  HWaddr f8:bc:12:3b:47:3f  
          inet addr:192.168.3.213  Bcast:192.168.3.255  Mask:255.255.255.0
          inet6 addr: fe80::fabc:12ff:fe3b:473f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5186 errors:0 dropped:908 overruns:0 frame:0
          TX packets:4723015 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:569811 (569.8 KB)  TX bytes:6430611558 (6.4 GB)
          Interrupt:47 

gre00     Link encap:UNSPEC  HWaddr C0-A8-03-D5-62-63-3A-31-00-00-00-00-00-00-00-00  
          inet addr:10.10.10.1  P-t-P:10.10.10.1  Mask:255.255.255.252
          inet6 addr: fe80::5efe:c0a8:3d5/64 Scope:Link
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1476  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


3) Then i start the smcroute daemon and start doing the rules:
$ sudo smcroute -d
$ sudo smcroute -a em2 192.168.113.100 239.255.1.1 gre00


About the second remark from Bombardil.
Yes you are correct, I see that on the supported interfaces the GRE tunnel is not present:

$more ip_mr_vif 
Interface      BytesIn  PktsIn  BytesOut PktsOut Flags Local    Remote
 0 em4               0       0  6257686848 4656017 00000 D503A8C0 00000000
 1 em1               0       0         0       0 00000 D57BA8C0 00000000
 2 em2        6257686848 4656017         0       0 00000 D571A8C0 00000000

Does this means that Ubuntu does not permit multicasts to be routed to it?
The strange is that i can ping the interface, and it as a static ip address.


Regards,

Manuel

**Comment by troglobit** [comment]
Had a similar question about tun interfaces in another project, troglobit/pimd#43, it mentions
altering the TTL value of the interface.  But I also notice now that the tun interface also has
the ALLMULTI flag set ...

**Comment by MPEIXOTO** [comment]
Hi,

I do not see any messages related to smcroute. Did it write in any special place?

After rebooting again the ubuntu I was able to execute the routing to the gre00 interface.
But it seems it is not doing it well, the routing. The multicast arrive on the other endpoint malformed.
The MTU/MSS seem to be set correctly.

Do you experienced similar issues?

Regards,

**Comment by MPEIXOTO** [comment]
Hello,

I have clean all and redo the configurations.

1)Done again the settings:
sudo ip tunnel add gre00 remote REMOTE_SERVER local 192.168.0.213 ttl 255 dev em2
 sudo ip link set gre00 up
 sudo ip link set gre00 multicast on  
 sudo ip addr add 10.10.10.1/30 broadcast 10.10.10.3 dev gre00

sudo echo 1 > /proc/sys/net/ipv4/ip_forward
sudo echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter

sudo smcroute -a em2 192.168.113.100 239.255.1.8 gre00


2) I see now that the routing is being done:

ip mroute
(192.168.113.100, 239.255.1.8)   Iif: em2        Oifs: gre00

3) But if i do a tcpdump -vv -i gre00 
I can not see any multicast traffic passing by this interface.

Do you have some idea why this happen?

Best regards,

Manuel

**Comment by bombadil** [comment]
@MPEIXOTO how do you generate your multicast traffic? Do you use mcsender that is part of smcroute? If yes: What command line options do you use?

**Comment by troglobit** [comment]
Sorry the extremely late reply!

The latest commits to SMCRoute master, with this fix 9f74eb4 to issue #13 in particular, include substantial changes to VIF enumeration which may help with this issue as well.

I don't know if you're still using smcroute, @MPEIXOTO or if you gave up. In either case it would be great to hear back from you!

**Comment by MPEIXOTO** [comment]
Hi,

A reply is always great even if a late one :).
Sadly I gave up, the pressure to find a solution obliged me to use a Cisco solution.
In future events I will give it another try.

Thanks Bombadil and Troglobit for the advises.

MPEIXOTO

**Comment by troglobit** [comment]
Thanks for the followup @MPEIXOTO :-)

**Comment by greenpau** [comment]
The error is from `cmdpkt.c`. it could be generated by either  [`iface_get_vif_by_name`](https://github.com/troglobit/smcroute/blob/master/cmdpkt.c#L182) or [`iface_get_mif_by_name`](https://github.com/troglobit/smcroute/blob/master/cmdpkt.c#L225).

The difference between the two function is IPv4 vs IPv6. As such the error is triggered by `iface_get_vif_by_name`.

The function is described in [`ifvc.c`](https://github.com/troglobit/smcroute/blob/master/ifvc.c#L194)

>  The virtual interface index if the interface is known and registered
 with the kernel, or -1 if no virtual interface by that name is found.

What does that mean...I wonder :smile: 

There is another function :smile: [`iface_find_by_name`](https://github.com/troglobit/smcroute/blob/master/ifvc.c#L89). 

I suspect the daemon cannot find it in `/proc/net/ip_mr_vif`.

> The ip_mr_vif file lists all the virtual interfaces involved in multicast operations 
see http://www.linuxjournal.com/article/6070

**Comment by greenpau** [comment]
> I suspect the daemon cannot find it in /proc/net/ip_mr_vif.

Got back to my original troubleshooting of `pimd`. I changed MTU from `8977` to `1400`. Now, I see the interface in  `/proc/net/ip_mr_vif`.

**Comment by greenpau** [comment]
and now the daemon accepted my commands:

````
# smcroute -a docker0 0.0.0.0 239.11.11.11 gre111 gre112
Sending command(s) ... OK!
#
````

**Comment by greenpau** [comment]
and I am receiving traffic on the other end of the tunnel.

**Comment by troglobit** [comment]
Huh, that was a big MTU @greenpau, usually it's 1476.
But it's great news you got it working! :smiley:

**Comment by greenpau** [comment]
> Huh, that was a big MTU @greenpau, usually it's 1476.

For some reason the MTU of a GRE interface is derived from a physical interface. In AWS, some instances come up with `ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001`.

I did not notice it until I (once again) went through my notes on multicast :smile: thankfully I was not yet desperate to open Rosen's Linux Kernel Networking.

**Comment by troglobit** [comment]
@greenpau That's very interesting, must add this to my FAQ!

Yeah, MTU mismatch can be a bit of a show stopper sometimes. Unfortunately [PMTU doesn't work with multicast](http://blog.ipspace.net/2015/09/path-mtu-discovery-doesnt-work-with-ip.html), so one is definitely left to manage that by hand, usually tunneling is the best way to go.

I just noticed the `pimreg` interface has an MTU of 1472, so that was probably the reason you had trouoble with pimd before.
