### ISSUE TITLE
Problem with smcroute and 224.0.0.x ip range

### ISSUE THREAD

**Issue by pparent76** [troglobit/smcroute#150]
Hi,

I have an un-understandable problem with smcroute 2.4.4 in openwrt 19.07.4

Basically smcroute recognizes and routes correctly packets with destination to 239.255.255.250, 225.255.255.250 , 224.0.1.56, ... But basically whatever is for 224.0.0.x does not seem to get recognized, no entry or paquet gets counted in "smcroutectl show routes" for those ips, despite it working perfectly well for other multicast ips.

I've been searching for hours, I really don't get why? Any idea ? Nothing seems to justify it.

Thank's a lot in advance.

**Comment by troglobit** [comment]
224.0.0.x is reserved for protocols on the link-local level.  They also usually have TTL 1, just to keep it link-local.  This is even mentioned in the wikipedia article, https://en.wikipedia.org/wiki/Multicast_address

**Comment by pparent76** [comment]
Thank's so much for your answer and your time, but then what If one really needs to forward them anyway across two networks, for example in order to discover with mDNS some devices on the other subnet, is it completely impossible?

**Comment by troglobit** [comment]
No, but then you likely are not looking for routed solutions, but rather bridged ones.  Some things are just not meant to be.

**Comment by pparent76** [comment]
Ok thanks a lot, unfortunately many Access Point (AP) manufactures, have bugs, and will cease to function, with multi-SSID when 2 SSIDs are bridge. Actually at first I had a bridged solution but I cannot keep it because it fails  with many AP models unfortunately....

Anyways I will see if I can do something with avahi proxy.

**Comment by troglobit** [comment]
Ah, I fully understand your predicament.  An mDNS proxy sounds like a good compromise!  Good luck :)
