### ISSUE TITLE
Same log entries

### ISSUE THREAD

**Issue by alexeys85** [troglobit/smcroute#151]
Seems like copy-paste typo, but anyway:
https://github.com/troglobit/smcroute/blob/7c8fdf0368879b2fa44cedc25ac3ebf0f96c9c86/src/inet.c#L104
and
https://github.com/troglobit/smcroute/blob/7c8fdf0368879b2fa44cedc25ac3ebf0f96c9c86/src/inet.c#L112
Has to be MC_ALL_ROUTERS in second case.

P.S. For what purpose it is necessary to join MC_ALL_SNOOPERS group as well?

**Comment by troglobit** [comment]
Yup, you're right.  

The `MC_ALL_SNOOPERS` group is used by the mrdisc code, [RFC4286](https://tools.ietf.org/html/rfc4286).

**Comment by alexeys85** [comment]
smcroute uses MC_ALL_SNOOPERS to send announces, but without any processing of the received announces?

**Comment by troglobit** [comment]
Ah, of course, my bad. True, that's not needed in the role SMCRoute has on the network. Thanks for pointing this out!

**Comment by troglobit** [comment]
Had a chance to look into this now, finally.  Turns out we support `IGMP_MRDISC_SOLICIT`, which is why we join both snoopers and routers.  At Westermo our switches (snooping devices) send solicitations on the snoopers address.

So everything as expected.  Copy-paste bug fixed earlier, in 178b19a.
