### ISSUE TITLE
mc_forwarding = 2  in multiple interfaces

### ISSUE THREAD

**Issue by schwartazi** [troglobit/smcroute#153]
Hi 
I notice that when I run the smcroute application, some of the interfaces are marked as mc_forwarding =1 and some mc_forwarding =2 
what does the mc_forwarding =2 means? is it a problem?
Thanks in advance
Adrian

**Comment by troglobit** [comment]
I'm guessing you're talking about `/proc/sys/net/ipv4/conf/$IFNAME/mc_forwarding`?  That's controlled by the kernel, not SMCRoute.  As far as I can see¹ it's a counter for when we create a VIF.  So as long as there's a multicast router running on that $IFNAME the `mc_forwarding` will be != 0.  I cannot say if it's wrong if it's >1.

____
¹ https://code.woboq.org/linux/linux/net/ipv4/ipmr.c.html

**Comment by schwartazi** [comment]
Can you elaborate what does the smcroute do that increment this counter?

**Comment by troglobit** [comment]
https://github.com/troglobit/smcroute/blob/34415585ada8eedced84a812492d1c457900d51c/src/mroute.c#L393

**Comment by troglobit** [comment]
Since this really isn't an issue with SMCRoute, maybe we can close it now?
