### ISSUE TITLE
Bi directional static routes

### ISSUE THREAD

**Issue by mellowcandle** [troglobit/smcroute#16]
I'm not sure that this is a bug, or routing protocol limitation.
But I would like to be able to define bi-directional static multicast routing.
Currently it doesn't work, it works only for one direction.

Here's the config I used:

### VA0 --> ETH0

    mgroup from va0 group 239.10.10.80
    mroute from va0 group 239.10.10.80 to eth0

### ETH0 --> VA0

    mgroup from eth0 group 239.10.10.80
    mroute from eth0 group 239.10.10.80 to va0

**Comment by bombadil** [comment]
Multicast is by definition unidirectional only. One sender is reaching multiple recipients with only one datagram. If the recipients want to send anything back they need to use unicast (remember, the unicast address of the sender is always known to the recipient, but not vice versa).

Micha

**Comment by troglobit** [comment]
Like @bombadil said, but also ... multicast by default acts like broadcast, if there's nothing stopping it,
e.g. IGMP or multicast routing protocols, it acts like broadcast.  Which is inherently dangerous.  That's
why many protocols and tools take special consideration for multicast.  For example, the standard ping
tool (iputils package) defaults to a TTL = 1 when the destination address is detected to be multicast.

The answer to your question is unfortunately no.  There is no way of establishing bi-directional
multicast routes in SMCRoute.  You need to add both mroute's to your .conf file.

**Comment by mellowcandle** [comment]
@bombadil 
Your right.
However, I have a non standard setup where each endpoint can also be a source of  multicast.
All the sources transmit on the same group (239.10.10.80)

I'm afraid that this can cause loops ETH0 <-- -> VA0
What do you think ?

**Comment by troglobit** [comment]
@mellowcandle Loops depends on you topology, or your endpoints.  If the endpoints simply echo back everything you send to them, all on the same group, that could potentially wreck havoc of your system.

**Comment by mellowcandle** [comment]
Well, apperently, I had an IP TABLES rule that screwed me. when I removed it. it works great.
So, if it was unknown till now, bi-directional routing works in smcroute

**Comment by troglobit** [comment]
Glad to hear you got it working, @mellowcandle :)
