### ISSUE TITLE
The -I NAME option seems to not work anymore

### ISSUE THREAD

**Issue by daniellerts** [troglobit/smcroute#163]
Even though the commit 900b9155a0a2e6c73c73f23b4e6d13b0bae3e108 states that "The -I NAME option remains for compatibility reasons", it seems like the [-I NAME] doesn't work anymore.

We are getting the error below when trying to use that option:
smcroutectl: invalid option -- 'I' 

smcroutectl: Unknown option -'?'

Can you check please?
Thanks.

**Comment by troglobit** [comment]
Are you using smcroute from the latest git master?

**Comment by daniellerts** [comment]
Yes.

**Comment by troglobit** [comment]
OK, found it. Should be fixed now. 

Please be aware, that there are still some heavy refactoring taking place on master atm.  There is a stable v2.5.0 planed within then next couple of weeks, or earlier even if I can finalize the refactor in mroute.c.

**Comment by daniellerts** [comment]
It works thanks!

We are running regression with master every night and if we will run into a problem, we will report to you here.
We have done that a few times before (e.g. Can't add previously deleted IPv6 multicast routes #132 by Ido Schimmel).

**Comment by troglobit** [comment]
Aha, nice, very appreciated. :)

**Comment by troglobit** [comment]
@daniellerts just fyi, the v2.5.0 release is now out -> https://github.com/troglobit/smcroute/releases/tag/2.5.0
