### ISSUE TITLE
Failed getting MFC stats: Address not available

### ISSUE THREAD

**Issue by NilsRo** [troglobit/smcroute#169]
Hi,

I am using smcroute with debian 10 and OpenWRT and it works fine normally. But on all system it throws the following error after a while and I have to restart the service to get it back running. During my internet research I cannot find anything about it (except the error message in the coding itself :-) ). Any hint what could cause the problem?

Tue Oct  5 22:05:12 2021 daemon.warn smcroute[3156]: Failed getting MFC stats: Address not available

Cheers,
Nils

PS. And also many thanks for creating it, works very nice to route DLNA/UPNP over my LAN to my flat living for work).

**Comment by troglobit** [comment]
Interesting. What version are you using?  That error should not be possible unless something really bad happened and the routing socket was closed (and vifs de-enumerated)

**Comment by troglobit** [comment]
OK, so the one before the huge refactor.  Much of that code was completely rewritten, and released in v2.5.0.  I'd recommend going for the latest release, v2.5.3, if you can.

Also, @bombadil is this something we should document in the Debian issue tracker as well?  Sounds a bit ominous that it can stop working like that :-/

**Comment by NilsRo** [comment]
Will build it on my server and test.

**Comment by bombadil** [comment]
> Also, @bombadil is this something we should document in the Debian issue tracker as well? Sounds a bit ominous that it can stop working like that :-/

If this is running on a kernel shipped by Debian we probably should do that.

@NilsRo, what kernel are you running? The default kernel provided by Debian?

**Comment by troglobit** [comment]
@NilsRo do you have any example config we can have a look at to try and reproduce the issue?  Would be neat to be able to confirm it is indeed fixed.  

Just FYI, we've been running SMCRoute for many years without any problems, in many different versions, not on Debian/Ubuntu but on dedicated embedded systems with custom configured Linux.  So I'm a bit puzzled at this bug report actually.

**Comment by NilsRo** [comment]
Attached my config. OpenWRT package is updated (done really fast :-) ). With debian everything is fine in the logs with new version and with OpenWRT I receive some new messages. But everything seems working fine. As the initial problem appears after some days I will watch it now.

Fri Oct  8 17:15:03 2021 daemon.err smcroute[3016]: Failed deleting VIF for iface lo: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcroute[3016]: Failed deleting MIF for iface lo: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcrouted[3016]: smcroute[3016]: Failed deleting VIF for iface lo: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcrouted[3016]: smcroute[3016]: Failed deleting MIF for iface lo: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcroute[3016]: Failed deleting VIF for iface lo: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcroute[3016]: Failed deleting MIF for iface lo: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcrouted[3016]: smcroute[3016]: Failed deleting VIF for iface lo: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcrouted[3016]: smcroute[3016]: Failed deleting MIF for iface lo: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcroute[3016]: Failed deleting VIF for iface ifb4eth0: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcroute[3016]: Failed deleting MIF for iface ifb4eth0: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcrouted[3016]: smcroute[3016]: Failed deleting VIF for iface ifb4eth0: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcrouted[3016]: smcroute[3016]: Failed deleting MIF for iface ifb4eth0: Resource temporarily unavailable
Fri Oct  8 17:15:03 2021 daemon.err smcroute[3016]: Failed enabling PIM IGMPMSG_WRONGVIF, ignoring: Protocol not available
Fri Oct  8 17:15:03 2021 kern.info kernel: [   36.623361] br-lan: port 2(wlan0) entered blocking state
Fri Oct  8 17:15:03 2021 kern.info kernel: [   36.623385] br-lan: port 2(wlan0) entered disabled state
Fri Oct  8 17:15:03 2021 kern.info kernel: [   36.628259] device wlan0 entered promiscuous mode
Fri Oct  8 17:15:03 2021 daemon.err smcrouted[3016]: smcroute[3016]: Failed enabling PIM IGMPMSG_WRONGVIF, ignoring: Protocol not available
Fri Oct  8 17:15:03 2021 daemon.notice smcroute[3016]: Ready, waiting for client request or kernel event.
Fri Oct  8 17:15:03 2021 daemon.err smcrouted[3016]: smcroute[3016]: Ready, waiting for client request or kernel event.

[smcroute.zip](https://github.com/troglobit/smcroute/files/7315182/smcroute.zip)

**Comment by NilsRo** [comment]
Hi.

More than a week... tap_muc is a VPN and created by the service. So I could be caused by it. But the issue appears also on my OpenWRT devices. There everything is encapsulated by a bridge and no VPN. But I upgraded the Firmware in that time perhaps that was a reason that some devices a restructured. I know that something was done there. Will take a look in the logs...

**Comment by NilsRo** [comment]
Softether. But before you spend time unnecessarily let me run the check with 2.5.3. Perhaps I can identify the reason or it will not happen anymore.

**Comment by troglobit** [comment]
Update: still running fine here, with SMCRoute 2.4.4, a week later.  So it's likely a problem with `tap_muc` being lost, as I mentioned before.

**Comment by NilsRo** [comment]
Hi. It happens also on my OpenWRT devices which are connected via bridges and are without Softether. But anyhow, with 2.5.3 I have not any issues. It is running without anything special behavior. So I will close it and everybody with OpenWRT can also use the use version. :-) So many thanks for your support.
