### ISSUE TITLE
Add support for a cache_lifetime feature timing out (*,G) rules

### ISSUE THREAD

**Issue by mellowcandle** [troglobit/smcroute#17]
I'm about to develop cache_lifetime feature for smcroute for my own use.
Would you be interested in that feature ?
I send you pull request.
Thanks.
Ramon

**Comment by troglobit** [comment]
I guess ... but please explain a bit more first :-)

**Comment by mellowcandle** [comment]
I have a very unique setup where the network topology is dynamic.
Multicast packets that once arrived from a specific IP through a specific interface appear later with the same IP from another interface.

I noticed that this causes the packets to drop in the kernel and be marked as Wrong packets in /proc/net/ip_mr_cache 

I figured that If I delete the routing once in a while, it will be recreated in the future with the right interface.

What do you think ?

**Comment by troglobit** [comment]
Hmm, that sounds a bit dangerous.  But I don't know your full setup, of course.  Little bit confused as to why you get Wrong packets?  Don't you have multiple rules in `/etc/smcroute.conf`to match all possible sender interfaces?

(Isn't there any way you could use a dynamic multicast router instead, like `mrouted`?)

**Comment by mellowcandle** [comment]
I do have. but still I get those when the topology changes.
I looked in the kernel multicast routing code and found that the reason is the interface is wrong.
reference code is here:
http://lxr.free-electrons.com/source/net/ipv4/ipmr.c#L1833
Am I wrong with my initial conclusion ?

**Comment by troglobit** [comment]
If you know all possible inbound interfaces for the sender of your multicast group(s), you can
add them to your `/etc/smcoute.conf`, like this:

    mroute from eth0 group 225.1.2.3 source 192.168.1.42 to eth1 eth2
    mroute from eth7 group 225.1.2.3 source 192.168.1.42 to eth1 eth2
    mroute from eth6 group 225.1.2.3 source 192.168.1.42 to eth1 eth2

That way you don't need to flush.

**Comment by mellowcandle** [comment]
I don't know the source IP...

**Comment by troglobit** [comment]
That's not a problem, it was just an example, just leave the `source 192.168.1.42` part out. But again, to _not_ know the source of the sender, or _where_ the sender is located is really asking for trouble. In particular if you have more than one producer of data for that group.  Be careful!

**Comment by mellowcandle** [comment]
Hey.
I implemented the feature and it works perfectly on my setup.
Basically, I added a new configuration option: "cache_lifetime" with seconds parameter.
When it parsed a recurrent timer is starting and whenever it expires it flushes all the dynamic routing list.

I'm using Linux, and I used timer_fd, so select() can return on a timer expired event.
This syscall (timer_fd) are linux specific, so I guess that if you're interested in this feature I need to implement it platform independent.
Let me know if you're interested.
Warm regards,
Ramon

**Comment by bombadil** [comment]
Hi Ramon,

feel free to share your changes needed for your cache lifetime timeout feature on github.com in a separate branch. Issues with support for other architecture can be sorted out separately later.

Best regards,
Micha

**Comment by troglobit** [comment]
:+1: to that, @bombadil

**Comment by mellowcandle** [comment]
By branch do you mean project fork?

**Comment by troglobit** [comment]
@mellowcandle fork, code and update this issue with a pointer to your branch/fork so we can inspect it.

**Comment by bombadil** [comment]
@mellowcandle I see you forked the repository to https://github.com/mellowcandle/smcroute but then didn't push any changes to it. If you like to share your code changes, please push them somewhere publicly accessible.

**Comment by mellowcandle** [comment]
Hi.
I actually did. but it's not portable, so I figured not pushing it upstream.
I used fd timer, and it exists only for Linux.
Thanks.
Ramon

**Comment by bombadil** [comment]
@mellowcandle, pushing to your own forked smcroute is not the same as pushing upstream. You can safely do so without interfering with our upsteram code. Please go ahead and push your changes to your fork on Github.

Regards,
Micha

**Comment by troglobit** [comment]
Agreed. I think many people would be interested to see your work, @mellowcandle!  And who knows, maybe someone can port your work to upstream (here) and add *BSD-support as well :smiley:

**Comment by mellowcandle** [comment]
I pushed the feature to my repository. We can close this now.
Thanks !

**Comment by troglobit** [comment]
Ah, now I understand what you did, that could actually be quite useful!

**Comment by mellowcandle** [comment]
Glad that you find it useful.
This solved the issue I had when the network topology once in a while changed and packets were dropped in the kernel.

**Comment by troglobit** [comment]
Yeah it figures. I started thinking about how one could make the feature more generic, not
just refactor the timer implementation for BSD compat.  There are two approaches I think:

1) Complement the timer with a packet counter check, if no packets routed for N seconds, prune route
2) Leverage the kernel `IGMPMSG_WRONGVIF` message, as discussed in #19 

(I'm reopening this, just silly discussing such a neat feature in a closed issue ;-)

**Comment by mellowcandle** [comment]
Great. if you need any assistance with coding of this feature let me know.

**Comment by troglobit** [comment]
I'll see if I can whip something up on a branch or so for you guys to test and comment on during the holidays :)

**Comment by troglobit** [comment]
This took a bit longer getting round to than I had hoped. Sorry!

Looking at the code now, what do you guys feel about replacing the timerfd code with `alarm(2)`, `SIGALRM`, or maybe `select(2)` on a dummy fd?  However do you create a dummy fd?

I definitely don't want to add threads, and the overhead of a *portable* event lib increases binary size to a ridiculous amount (tried that already).

**Comment by mellowcandle** [comment]
Hey.
I prefer not working with signals if possible, they're error prone and have
lot's of compatibility issues.
Which library did you use for events ? libevent ? maybe there's smaller.

Thanks.
Ramon

**Comment by troglobit** [comment]
Hi @mellowcandle,

Agreed, signals should be avoided ... or serialized. I've used libev a lot in the past, and even written my own, [libuev](https://github.com/troglobit/libuev) which is much smaller, but not portable to *BSD kqueue yet.

Anyway, I did a quick hack using `gettimeofday()` and added a simple timeout to `select()`.  The timeout setting is read from the command line for now, but at least there's something that should be portable  
- https://github.com/troglobit/smcroute/tree/cache-lifetime

**Comment by mellowcandle** [comment]
Nicely done.

**Comment by bombadil** [comment]
I've added a comment on commit f49d9adccc4e715fda55eda5420ea3a798b597a3.

**Comment by troglobit** [comment]
@bombadil: Thanks for the audit! My code looks like crap, and your version is a lot better. Thanks!

I'm pasting it here in case I force-push to the cache-timeout branch later.

```C
    /* Micha's version ... */
    if (last_flushed.tv_sec + cache_tmo < now.tv_sec) {
        last_flushed = now;
        smclog(LOG_NOTICE, "Cache timeout, flushing all (*,G) routes!");
        mroute4_dyn_cache_delete();
    }
```

**Comment by bombadil** [comment]
Can you please consider to stop using force-pushes? It makes collaboration unnecessarily hard.

When using the commit comment function (as I did in this case), the necessary rebase in your force-push based workflow will change the commit hash, so that others won't find the discussion anymore when they look through the commit history on Github. The comments will still stick to the old commit hash.

**Comment by bombadil** [comment]
@troglobit, you wrote:
> I'm pasting it here in case I force-push to the cache-timeout branch later.

Why not just commit and push it? I've done that in commit 3a89bbf.

**Comment by bombadil** [comment]
Just for the records, the Travis CI build failure reported for commit 3a89bbf is because this branch is out of date. It should build successfully when merging in master or when rebasing.

**Comment by troglobit** [comment]
@bombadil Sure, did not realize this habit of mine was annoying you. I try to rebase and squash commits as often as possible to get a clean history when merging to master. In particular on experimental branches like this.

Also, did not expect collaboration in the form of code, at all. Thank you!

**Comment by troglobit** [comment]
Travis-CI: Noted :+1:

**Comment by bombadil** [comment]
@troglobit rebase and squashes and what not are all fine, and I do use them also a lot - but only on local commits. For already pushed commits I do real merges. This way you don't need force-pushes on a regular basis.

**Comment by troglobit** [comment]
@bombadil OK. So even pushed experimental/feature branches you do not rebase before merging to master?  That takes a lot of discipline ... but I promise to better myself, at least here in the smcroute project! :)

**Comment by bombadil** [comment]
Yes, also for experimental/feature branches, for the following reason: A merge commit nicely shows publicly that a branch has been dealt with. All commits of that experimental/feature branch are then part of the _official_ history provided in the master branch.

**Comment by troglobit** [comment]
Hmm OK, despite the obvious loss of freedom to the individual developer and the occasional goofed up commits + followup-commits, I can see the merits of that approach :+1: 

Are we laying the foundations for a `CONTRIBUTING.md` document now? :smiley:

**Comment by bombadil** [comment]
If you would like to have that, please go ahead. Everybody is welcome to contribute. :+1:

**Comment by troglobit** [comment]
I was just thinking, because there we could lay out the ground rules for working with the project on various levels.  GitHub even adds a neat clickable banner "Read the contribution guidelines for this project" when someone does a pull request or files an issue. 

I really appreciate your feedback on collaborating with GIT, even though I may sound like a grumpy old man from time to time! :smirk:

**Comment by mellowcandle** [comment]
Hey. any updates for this feature. would love seeing it get's merged :)

**Comment by troglobit** [comment]
Hi, sorry for the delay!  I noticed I had forgotten about this one today.  Will release a v2.2.1 tomorrow or so, then I'll get on this for the v2.3 series.

**Comment by troglobit** [comment]
Merged to master, finally :smiley: 

I also took the liberty of adding a `-F` client command to immediately flush (*,G) routes, which should be useful when a topology change is detected, e.g. in a keepalived (VRRP) callback when a router goes from master to backup.
