### ISSUE TITLE
Fails to build when git is not available

### ISSUE THREAD

**Issue by bombadil** [troglobit/smcroute#176]
The released tar archive https://github.com/troglobit/smcroute/releases/download/2.5.4/smcroute-2.5.4.tar.gz doesn't build anymore when Git is not installed in the build environment:
```
sh: 1: git: not found
configure.ac:9: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:9: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
dh_autoreconf: error: autoreconf -f -i returned exit code 1
```
The build logs logs can be found here:
https://salsa.debian.org/debian/smcroute/-/jobs/2183105
and even the full source directory is available here for further investigation:
https://salsa.debian.org/debian/smcroute/-/jobs/2183105/artifacts/browse/debian/output/ (see folder source_dir).

I didn't look into further details yet, but I wanted to let you know early.

Cheers

**Comment by troglobit** [comment]
Ouch, forgot about the `dh_autoreconf` step in Debian! :-/

Thanks for letting me know, I'll revert that change in a61969d and go back to stepping the version manually.  Terribly sorry about this!

**Comment by troglobit** [comment]
Reverted in 4302689, prepared for another patch release.  However, I'd recommend going for v2.5.3 + backport of these patches, since I won't be able to make another release for a few days:

  - 8ce1d11
  - bdbde09
  - a0e7758

Again, sorry about the mess! :-/

**Comment by troglobit** [comment]
FYI: We just had another minor fix go in this morning, so I'll start the release process and will hopefully get a 2.5.5 out by the end of the week.

**Comment by bombadil** [comment]
If it is just a matter of days, no need to rush anything. I'll just wait for 2.5.5 to be released then.

**Comment by troglobit** [comment]
There, [v2.5.5 release](https://github.com/troglobit/smcroute/releases/tag/2.5.5) available now.
