### ISSUE TITLE
Latest release linked on homepage is 2.5.0

### ISSUE THREAD

**Issue by jpalus** [troglobit/smcroute#181]
Just a minor observation that [homepage](https://troglobit.com/projects/smcroute/) has a link to release 2.5.0 while latest version as of this writing is 2.5.5. I think it would be good to either upload latest version or just link to GitHub releases instead.

**Comment by troglobit** [comment]
Ah, thanks! I've been meaning to automate updating those links, I'll have a look at it during the weekend :-)

**Comment by troglobit** [comment]
Fixed and pushed to .com and .io pages.
