### ISSUE TITLE
Null pointer dereference

### ISSUE THREAD

**Issue by alexeys85** [troglobit/smcroute#186]
I've encountered a problem when using reload config command from `smcroutectl`. Stacktrace shows that this `if` statement:
https://github.com/troglobit/smcroute/blob/cf5cc48d0b360a8cc391bd72ed0eee3475d0b5e0/src/pidfile.c#L77-L78
becomes `true` and `NULL` passes to `utimensat` function with following dereference:
https://github.com/troglobit/smcroute/blob/cf5cc48d0b360a8cc391bd72ed0eee3475d0b5e0/lib/utimensat.c#L36

**Comment by troglobit** [comment]
Interesting, you're triggering the replacement function. What libc are you building against?

**Comment by troglobit** [comment]
(Obviously I'll get on it to fix the `utimensat()` replacement, I'm just curious.)

**Comment by alexeys85** [comment]
Well, I'm using Ubuntu 22.04 and just wrongly included `utimensat.c` to build :)

**Comment by troglobit** [comment]
Aha, well that should be automatically detected by the configure script.  If you're doing some sort of hybrid build, you don't need it on GLIBC.  Also, please remember the GNU license restrictions and implications if you're incorporating parts/whole of SMCRoute in another application.

**Comment by alexeys85** [comment]
We don't incorporate any parts of SMCRoute in our apps. I just wanted to add cmake support :)

**Comment by troglobit** [comment]
OK, got it!  Then FYI, all the stuff in `lib/` are replacement functions in case the system doesn't have it.
