### ISSUE TITLE
Multipath multicast routing

### ISSUE THREAD

**Issue by danrosenqvist** [troglobit/smcroute#19]
Hi,
I've set up the following network where Node1 and Node6 are transmitting and 
receiving multicast traffic to group 224.1.1.1 on port 25252. The intermediate
nodes are only forwarding multicast traffic. All nodes have ip forwarding and
multicast support turned on. Reverse path filtering is also turned off as we
use multiple paths to the destinations.
```
                                 Node3
                              +---------+
                              |         |
                           +--+eth0 eth1+--+
                           |  |         |  |
   Node1          Node2    |  +---------+  |    Node5          Node6
+---------+    +---------+ |               | +---------+    +---------+
|         |    |     eth1+-+               +-+eth0     |    |         |
|     eth0+----+eth0     |                   |     eth2+----+eth0     |
|         |    |     eth2+-+               +-+eth1     |    |         |
+---------+    +---------+ |     Node4     | +---------+    +---------+
                           |  +---------+  |
                           |  |         |  |
                           +--+eth0 eth1+--+
                              |         |
                              +---------+
```
```
+-------+-----------+------------+---------+----------+
| Node  | Interface | IP address | Netmask | Gateway  |
+-------+-----------+------------+---------+----------+
| Node1 | eth0      | 10.0.1.1   | 24      | 10.0.1.2 |
+-------+-----------+------------+---------+----------+
| Node2 | eth0      | 10.0.1.2   | 24      | 10.0.1.1 |
+-------+-----------+------------+---------+----------+
|       | eth1      | 10.0.2.2   | 24      | 10.0.2.3 |
+-------+-----------+------------+---------+----------+
|       | eth2      | 10.0.3.2   | 24      | 10.0.3.4 |
+-------+-----------+------------+---------+----------+
| Node3 | eth0      | 10.0.2.3   | 24      | 10.0.2.2 |
+-------+-----------+------------+---------+----------+
|       | eth1      | 10.0.4.3   | 24      | 10.0.4.5 |
+-------+-----------+------------+---------+----------+
| Node4 | eth0      | 10.0.3.4   | 24      | 10.0.3.2 |
+-------+-----------+------------+---------+----------+
|       | eth1      | 10.0.5.4   | 24      | 10.0.5.5 |
+-------+-----------+------------+---------+----------+
| Node5 | eth0      | 10.0.4.5   | 24      | 10.0.4.3 |
+-------+-----------+------------+---------+----------+
|       | eth1      | 10.0.5.5   | 24      | 10.0.5.4 |
+-------+-----------+------------+---------+----------+
|       | eth2      | 10.0.6.5   | 24      | 10.0.6.6 |
+-------+-----------+------------+---------+----------+
| Node6 | eth0      | 10.0.6.6   | 24      | 10.0.6.5 |
+-------+-----------+------------+---------+----------+
```

The smcroute rules are set up as follows (per node).
Node2:
```
smcroute -a eth0 0.0.0.0 224.1.1.1 eth1 eth2
smcroute -a eth1 0.0.0.0 224.1.1.1 eth0
smcroute -a eth2 0.0.0.0 224.1.1.1 eth0
```

Node3:
```
smcroute -a eth0 0.0.0.0 224.1.1.1 eth1
smcroute -a eth1 0.0.0.0 224.1.1.1 eth0
```
Node4:
```
smcroute -a eth0 0.0.0.0 224.1.1.1 eth1
smcroute -a eth1 0.0.0.0 224.1.1.1 eth0
```

Node5:
```
smcroute -a eth0 0.0.0.0 224.1.1.1 eth2
smcroute -a eth1 0.0.0.0 224.1.1.1 eth2
smcroute -a eth2 0.0.0.0 224.1.1.1 eth0 eth1
```
Upon setting these rules I can clearly see traffic going from Node1 to Node6 
and vice versa. Looking closer at the multicast routing cache for Node2 and 
Node5 (which are the nodes responsible for path selection in each respective
direction) we can see that only one of the paths have been added:

Node2:
```
root@Node2:~# smcroute -a eth0 0.0.0.0 224.1.1.1 eth1 eth2
root@Node2:~# smcroute -a eth1 0.0.0.0 224.1.1.1 eth0
root@Node2:~# smcroute -a eth2 0.0.0.0 224.1.1.1 eth0
root@Node2:~# ip mroute
(10.0.6.6, 224.1.1.1)            Iif: eth2       Oifs: eth0 
(10.0.1.1, 224.1.1.1)            Iif: eth0       Oifs: eth1 eth2 
root@Node2:~# 
```
Node5:
```
root@Node5:~# smcroute -a eth0 0.0.0.0 224.1.1.1 eth2
root@Node5:~# smcroute -a eth1 0.0.0.0 224.1.1.1 eth2
root@Node5:~# smcroute -a eth2 0.0.0.0 224.1.1.1 eth0 eth1
root@Node5:~# ip mroute
(10.0.1.1, 224.1.1.1)            Iif: eth1       Oifs: eth2 
(10.0.6.6, 224.1.1.1)            Iif: eth2       Oifs: eth0 eth1 
root@Node5:~# 
```
This occurs even though reception of multicast traffic occurs on both 
interfaces.

Node2:
```
root@Node2:~# tcpdump -i eth1 -vvv                 
tcpdump: listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
09:08:40.969403 IP (tos 0x0, ttl 8, id 11203, offset 0, flags [DF], proto UDP (17), length 32)
    10.0.6.6.42032 > 224.1.1.1.25252: [udp sum ok] UDP, length 4
09:08:43.927778 IP (tos 0x0, ttl 9, id 20464, offset 0, flags [DF], proto UDP (17), length 32)
    10.0.1.1.36171 > 224.1.1.1.25252: [udp sum ok] UDP, length 4

root@Node2:~# tcpdump -i eth2 -vvv
tcpdump: listening on eth2, link-type EN10MB (Ethernet), capture size 262144 bytes
09:09:18.949115 IP (tos 0x0, ttl 9, id 32333, offset 0, flags [DF], proto UDP (17), length 32)
    10.0.1.1.36171 > 224.1.1.1.25252: [udp sum ok] UDP, length 4
09:09:20.983309 IP (tos 0x0, ttl 8, id 29307, offset 0, flags [DF], proto UDP (17), length 32)
    10.0.6.6.42032 > 224.1.1.1.25252: [udp sum ok] UDP, length 4
```
Node5:
```
root@Node5:~# tcpdump -i eth0 -vvv
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
09:09:54.154853 IP (tos 0x0, ttl 9, id 53322, offset 0, flags [DF], proto UDP (17), length 32)
    10.0.6.6.42032 > 224.1.1.1.25252: [udp sum ok] UDP, length 4
09:09:57.128041 IP (tos 0x0, ttl 8, id 54402, offset 0, flags [DF], proto UDP (17), length 32)
    10.0.1.1.36171 > 224.1.1.1.25252: [udp sum ok] UDP, length 4

root@Node5:~# tcpdump -i eth1 -vvv
tcpdump: listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
09:11:57.207701 IP (tos 0x0, ttl 8, id 43515, offset 0, flags [DF], proto UDP (17), length 32)
    10.0.1.1.36171 > 224.1.1.1.25252: [udp sum ok] UDP, length 4
09:11:59.230905 IP (tos 0x0, ttl 9, id 50499, offset 0, flags [DF], proto UDP (17), length 32)
    10.0.6.6.42032 > 224.1.1.1.25252: [udp sum ok] UDP, length 4
```

As we can see from the multicast routing cache the path selected for 
transmitting the information between Node1 and Node6 is through Node4.
If we were to disable one of the interfaces on Node4, the expected behavior 
would be a new path selection (through Node3). However, this does not happen
even though the multicast traffic is still received in both Node2 and Node5.

My theory for what's causing this behavior is related to how smcroute handles
multipath routes. Typically on receiving multicast traffic, the kernel will
signal the userspace daemon by means of a IGMPMSG_NOCACHE message indicating
that no route exist in the cache for the given multicast packet. In this case
however, the route exists but not from the given interface, thus causing the
kernel to transmit an IGMPMSG_WRONGVIF message instead.

Regards,
Dan

**Comment by troglobit** [comment]
Thank you for taking the time to report this here, Dan!  I agree with your
conclusion, and like I said in our email correspondence earlier, I'll start
setting up a test by myself to see if I can reproduce and craft a fix.

**Comment by danrosenqvist** [comment]
Great, thank you for taking time to look at the rocket-science stuff! :)

Let me know if you need any additional information from my environment and I'd be happy to help!

**Comment by troglobit** [comment]
Hmm, from what I can derive from your setup, without having set anything up myself yet, your problem atm. is that Node5 does not "fail over" to the secondary stream.  However, I believe Node5 will continuously get `IGMPMSG_WRONGVIF` even during normal operation, so when should SMCRoute fail-over to the secondary stream?  You don't want a) duplicate frames (that's the reason as to why not both streams are possible to forward at the same time) and b) constant flapping between sources in non-fail-over conditions.  The only thing we would have to go on in a fail-over mechanism is the multicast frame counters, i.e. check if they've stopped moving for the currently installed route ... 

I'll see what I can come up with, but atm. it feels much like what you need is a link-state protocol underneath that can handle your usecase.  Maybe [mrouted](https://github.com/troglobit/mrouted/) or [pimd](https://github.com/troglobit/pimd/) can be of help, have you considered them, at least for Node2 — Node5?

**Comment by danrosenqvist** [comment]
I agree with you to some extent, we don't want the constant flapping that you mentioned, and it's likely we get the IGMPMSG_WRONGVIF continously. 

But in this case, is it up to the routing service to perform the duplicate packet detection? In bot DV and LS routing protocols the path is determined and packets forwarded accordingly, but in this case I would like to forward all packets and leave it up to either a) the protocol (for TCP) or b) the application (for UDP) to perform duplicate packet detection. Would this cause issues when using multicast?

In our current solution neither mrouted nor pimd is viable as we'd like to minimize the overhead as well as the convergence time.

**Comment by troglobit** [comment]
Sounds a little bit like what you *really* need is doing this entirely in a layer-2 setting, leaving it up to protocols like RSTP, PRP/HSR, or similar to reconfigure the topology or duplicate packets. But if you want to do this on layer-3, on Linux/UNIX, I *think* you may be out of luck ... 

If I've understood the mechanisms of `IGMPMSG_WRONGVIF`, after reading up on it, one of the reasons for it existing in the first place is for the kernel to be able to alert the layer-3 multicast routing daemon of possible (unicast) route changes, so it (mrouted/pimd) can adjust the multicast routes accordingly. Because receiving multicast from the same source to the same group (S,G) from multiple paths is considered an error condition, which I believe stems from preventing layer-3 loops. Otherwise there would be no protection, other than the wisdom of the administrator, from preventing Node5 to forward the same multicast back towards Node2. 

OK, there *may* exist some magic in the kernel which can unlock this and allow you to do whatever you want, but I doubt it. Maybe there is some way of redirecting all your traffic to a `tun` interface and do all the routing (and packet de-duplication) in userspace?

Terribly sorry to disappoint you like this! :disappointed:

**Comment by danrosenqvist** [comment]
Ok, thank you for your time! 

As a side-note FreeBSD seem to support this "feature" (https://www.freebsd.org/cgi/man.cgi?query=multicast&sektion=4&manpath=FreeBSD+5.2-RELEASE):
```
     The MRT_MFC_FLAGS_DISABLE_WRONGVIF flag is used to explicitly disable
     the IGMPMSG_WRONGVIF kernel signal at the (S,G) granularity if	a mul-
     ticast data packet	arrives	on the wrong interface.	 Usually, this signal
     is	used to	complete the shortest-path switch in case of PIM-SM multicast
     routing, or to trigger a PIM assert message.  However, it should not be
     delivered for interfaces that are not in the outgoing interface set, and
     that are not expecting to become an incoming interface.  Hence, if	the
     MRT_MFC_FLAGS_DISABLE_WRONGVIF	flag is	set for	some of	the inter-
     faces, then a data	packet that arrives on that interface for that MFC
     entry will	NOT trigger a WRONGVIF signal.	If that	flag is	not set, then
     a signal is triggered (the	default	action).
```

**Comment by troglobit** [comment]
Yeah, FreeBSD has a newer version of the MROUTING API, which is very cool.  I did not know about this particular feature, which looks very interesting.  It's still a bit unclear to me though if that would have helped your situation.

**Comment by danrosenqvist** [comment]
From the contents of the kernel code it seems that packets are dropped regardless if a WRONGVIF message is created or not (just based on the incoming interface). I'll try some kernel hacking and hope to solve this issue there instead.

**Comment by troglobit** [comment]
OK, as I suspected ... good luck @danrosenqvist! :smiley:
