### ISSUE TITLE
asuswrt-merlin compatibility

### ISSUE THREAD

**Issue by privacyguy123** [troglobit/smcroute#200]
As far as I can see these firmware routers run mcpd whether or not IGMP Proxy is on or off which makes smcroute complain API is already in use.

```
smcrouted -n
smcroute[8890]: SMCRoute v2.5.6
smcroute[8890]: IPv4 multicast routing API already in use: Address already in use
```

If I killall mcpd the inbuilt WireGuard Server function of the router firmware fails to connect which defeats the purpose of routing the packets inside the WG Server tunnell ...

Is there a way to make this stuff coexist?

**Comment by troglobit** [comment]
Converting to Discussion since this is not a bug or feature request in the SMCRoute project but more of a general question.
