### ISSUE TITLE
smcroute stops routing traffic after a minute

### ISSUE THREAD

**Issue by jayfry1077** [troglobit/smcroute#206]
I installed smcroute and got it working with /etc/smcroute.conf

its correctly forwarding traffic to my other interface (docker virtual network) and everything works.

after about a minute the traffic stops flowing

I restart smcroute, traffic flows again

Checking the logs I cannot see any errors reporting, and I see the service is still in a running state.

not sure what information I can provide to better understand this issue, please let me know.

**Comment by troglobit** [comment]
Quite sure this is not a problem with SMCRoute, sounds more like a problem with your network.  But it's incredibly hard to say anything seeing as you've not included anything about your configuration, network topology, multicast streams, and your expected outcome.

**Comment by troglobit** [comment]
ETIMEDOUT
