### ISSUE TITLE
Crashes when adding v6 route on a kernel without v6 multicast support

### ISSUE THREAD

**Issue by kuba-moo** [troglobit/smcroute#207]
Hi!

This line leads to a crash:

https://github.com/troglobit/smcroute/blob/cd259302b008205071b8ad81a2184a681e207cba/src/conf.c#L238

when adding a v6 route and kernel has no v6 mcast support. vif is equal to NO_VIF.

**Comment by troglobit** [comment]
Nice catch, `NO_VIF` == `ALL_VIFS` == -1, so that makes sense.  We should add a check to the return of `iface_get_vif()`, I'll get right on it.

**Comment by troglobit** [comment]
Thank you for taking the time to report this!  The issue has been fixed and released as [SMCRoute v2.5.7](https://github.com/troglobit/smcroute/releases/tag/2.5.7)
