### ISSUE TITLE
404 for https://troglobit.com/projects/smcroute/smcroute-conf.html

### ISSUE THREAD

**Issue by 532910** [troglobit/smcroute#211]
![image](https://github.com/user-attachments/assets/c8d54f2a-d1a6-4acc-b650-442c3c3f1091)

**Comment by 532910** [comment]
it is in the Features list on https://troglobit.com/projects/smcroute:

![image](https://github.com/user-attachments/assets/905123c1-bb7d-4e08-9411-40e15d115984)

**Comment by troglobit** [comment]
Same example also available in the source distribution, or here directly on GitHub.  See
https://github.com/troglobit/smcroute/blob/master/smcroute.conf

**Comment by troglobit** [comment]
Fixed.
