### ISSUE TITLE
Add new kernel (include patch) feature to *not* enable ALLMULTI on VIFs

### ISSUE THREAD

**Issue by troglobit** [troglobit/smcroute#27]
When VIFs are registered the kernel implicitly adds the ALLMULTI flag to allow all multicast to ingress the interface. This is useful for PIM and DVMRP, but not for low-resource CPU's that know exactly what it wants to forward.

This is an optimization which can _only_ be used with `(S,G)` routes.  The relatively new `(*,G)` support in SMCRoute relies on the kernel `IGMP_NOCACHE` feature to alert the daemon when new unknown multicast arrives on an interface.  On FreeBSD `(*,G)` kernel support is included, newer MROUTING stack, but to support `(*,G)` on Linux the kernel would need to be upgraded.

Hence, when this optimization feature is added it is important not only to document the limitations, but also to add (at least) warnings if the user adds `(*,G)` routes in `smcroute.conf` or from the smcroute client.

**Comment by bombadil** [comment]
Hmm, this reads like it is a userspace work-around for a Linux kernel issue. Do we really want this?

If this assessment is true, then in the long run I would really like to get rid of it again.

**Comment by troglobit** [comment]
@bombadil  It's actually an out-of-tree kernel patch + a VIF flag passed to the kernel when enumerating VIFs.  I will, in time, attempt to upstream this to at least Linux because kernels usually only cater to dynamic multicast routing daemons.

**Comment by troglobit** [comment]
Postponing this for a later release.

**Comment by nihilus** [comment]
Is the patch available anywhere? I dont want br0 to be set to allmulti in my embedded products.

**Comment by troglobit** [comment]
@nihilus Just spent a few hours trying to hunt down this patch, but alas no luck.  I saw traces of it in an older kernel version we used, but that was for bridge with switchdev offloading.  We've scrapped that approach for now, but we'll likely need something later on for our aging ARMv5 fleet of devices that need SMCRoute support.

I'm letting this issue remain open though, I have a few other places to check, but not available until after the winter holidays.

**Comment by nihilus** [comment]
Nice, I will give 2.3.1 a new try. I had some problems with invalid input interfaces, 2.0.0 worked flawless though.

**Comment by nihilus** [comment]
@troglobit ended up hacking up igmpproxy to do all the work, however routing SSDP seems to be a flaky thing (even with minissdpd (which needs to be killed and restarted) so I will just fix up the unicast route on demand.

**Comment by troglobit** [comment]
Closing this since I've not found the patch and no longer need it.  The `smcrouted -N` with the `-t ID` and `-I NAME` options also help run different instances of SMCRoute where you can navigate around many of the issues I originally intended.
