### ISSUE TITLE
Add support for disabling interfaces

### ISSUE THREAD

**Issue by troglobit** [troglobit/smcroute#28]
When SMCRoute starts up it probes the system for valid interfaces and enumerates VIF's in the kernel.  All non-loopback multicast capable interfaces are considered valid.  On Linux they do not even need to have an IP address, enumeration is done as is on IPv6, using `ifindex`.

However, when a VIF is enumerated (created) the kernel, at least Linux, will automatically set the `ALLMULTI` flag -- meaning "please ingress ALL multicast on this interface, we're a routing machine!".  On low-resource systems this may not be a side effect you like, in particular if you have many interfaces but only route multicast between a few, or a pair.

This feature request details a way do declare interfaces as disabled or enabled, and thus enumerate VIFs only on the actual multicast routing interfaces.

### Step One

In `/etc/smcroute.conf`:

    # By default, all non-loopback multicast capable interfaces are enabled.
    # If you want to use loopback, set the interface multicast flag on it.
    phyint eth0 disable

### Step Two

    $ smcroute -N

In `/etc/smcroute.conf`:

    # With -N no VIFs are enumerated by default, all interfaces must be enabled
    # in the config file before attempting to enumerate.
    phyint eth0 enable

**Comment by bombadil** [comment]
Improvement suggestion on the config syntax:
```
phyint <enable|disable> interface [interface ...]
```
This way you can enable/disable multiple interfaces in one config line.

**Comment by troglobit** [comment]
@bombadil good idea, but I was considering to possibly add more per-interface settings over time.

For instance, looking at pimd it has the following settings, most of which only applies to dynamic routing protocols:

    phyint <local-addr | ifname>
            [disable | enable] [igmpv2 | igmpv3]
            [dr-priority <1-4294967294>]
            [ttl-threshold <1-255>] [distance <1-255>] [metric <1-1024>]
            [altnet <network> [/<masklen> | masklen <masklen>]]
            [scoped <network> [/<masklen> | masklen <masklen>]]

For SMCRoute it would be neat to be able to control/adjust the TTL of inbound multicast and set up scoping (filtering) based on TTL or even source address (ref. `(*,G)` routes).  

But we can for sure start out with your syntax!

    phyint <enable|disable> interface [interface ...]

:+1:

**Comment by bombadil** [comment]
No, if you intend to add more interface related settings, then your initial suggested syntax perfectly makes sense. Let's stick with your initial syntax. :+1:

**Comment by troglobit** [comment]
OK :+1: 

I think one usually have one of two use-cases:
- disable on a few/handful
- enable on a few/handful

so the `-N` command line option to toggle default enable/disable VIFs on all interfaces should be sufficient.

**Comment by bombadil** [comment]
:+1:
