### ISSUE TITLE
Maybe remove smcroute.init from distribution and GIT?

### ISSUE THREAD

**Issue by troglobit** [troglobit/smcroute#29]
Since most major distributions already have, or are switching to systemd maybe we can drop the `smcroute.init` file from the tree?

Personally I rarely run the SMCRoute my distribution (Ubuntu or Debian) carries, but both run systemd. Most often I run SMCRoute in [TroglOS](https://github.com/troglobit/troglos), for testing, or in our embedded Linux distribution at work¹. In both the latter two cases we use [Finit](https://github.com/troglobit/finit) instead of SysV init.

I have no means or interest to maintain this init script and sometime I get support requests via email.

Can we remove it?

¹) http://www.westermo.com

**Comment by bombadil** [comment]
I would like to maintain the init script for a while. If you get any issues reported related to it, please let me know and I will take care of it.

Of course I do welcome contributions to support other boot initialization systems too.

**Comment by troglobit** [comment]
OK awesome, thanks! :smiley: 

The latest report I got was basically along the lines of "Help, wut now?" with this attached:

```shell
root@mcast:/etc/smcroute# /etc/init.d/smcroute start
Starting static multicast router daemon: ERRO: MRT_ADD_VIF eth0ERRO: MRT_ADD_VIF eth0Ix 21 Fl 0ADD_VIF eth0Ix 21 Fl 0h0Note: adh0Ix 21 Fl 0h0Note: ad 0x0000 IP 0h0Note:
root@mcast:/etc/smcroute# 
```

I don't know what `log_progress_msg` does, but everything on one line like that looks a bit odd. Unclear what version the reporter used, unfortunately.

**Comment by bombadil** [comment]
Well, init scripts do have their deficiencies...

`log_progress_msg` can be used to provide a nice progress indicator. Or, in this case it is (ab)used to provide at least a minimal reason string in case the smcroute daemon could not get started.

The output shown above probably means that starting the smcroute daemon produced some output in an unexpected format. Potentially the init script was not even interpreted by `/bin/sh` (as specified in the shebang) because the prefix `ERRO: ` didn't get stripped (shell variable interpolation) as intended.

**Comment by troglobit** [comment]
He he ;-)

I suspected as much. In [Inadyn](https://github.com/troglobit/inadyn/blob/master/include/error.h) we return a defined error code to the user when the daemon exits. Maybe that could help here as well?

(In this particular case I suspect some issue with interfaces when enumerating VIFs.)

**Comment by bombadil** [comment]
@troglobit, you mentioned above:
> Personally I rarely run the SMCRoute my distribution (Ubuntu or Debian) carries, but both run systemd.
Do you have by chance a systemd unit script or so that you could share?

**Comment by troglobit** [comment]
No I don't ... but maybe something like this would help?

```shell
cat > /usr/lib/systemd/system/smcroute.service << EOF
[Unit]
Description=Static Multicast Routing Daemon
After=syslog.target network.target
ConditionPathExists=/etc/smcroute.conf

[Service]
Type=simple
EnvironmentFile=-/etc/sysconfig/smcroute
ExecStart=/usr/sbin/smcroute -d -n

[Install]
WantedBy=network.target
EOF
```

**Comment by troglobit** [comment]
OK, let's keep the init file for the time being. I've just added a systemd unit file as well for the v2.2 release.

Closing.
