### ISSUE TITLE
Proposal: remove mcsender from distribution and GIT

### ISSUE THREAD

**Issue by troglobit** [troglobit/smcroute#30]
The `mcsender` application distributed with SMCRoute is a simple UDP multicast generator that is only barely more interesting than using the standard ping (Debian [iputils-ping](https://packages.qa.debian.org/i/iputils.html)).  Barely, because ICMP can be blocked on the path between sender and receiver, which is the only real downside of using ping over mcsender.

The `mcsender` application has fallen behind in maintenance and should be both cleaned up and aligned with the overall coding style in SMCRoute if we want to continue maintaining it.  However, I'd much rather see it be dropped for an actual multicast testing application (sender *and* receiver).  Here [iperf](https://packages.qa.debian.org/i/iperf.html) and [omping](https://github.com/troglobit/omping) stand out as clear cut alternatives we should recommend instead.

**Comment by bombadil** [comment]
`mcsender` provides only a few features. Are all of them supported by the alternatives you mentioned? If yes, please feel free to drop it.

The manpage should then get amended to mention the tools that are recommended for testing multicast.

**Comment by troglobit** [comment]
Standard ping is the only one that doesn't support all features, and only because you cannot set the UDP port. Iperf and omping are awesome replacements.

I'll update the man page in the same go. Thank you for your prompt feedback!
