### ISSUE TITLE
Add support for IPv6 wildcard routes

### ISSUE THREAD

**Issue by schuerg** [troglobit/smcroute#31]
I think there is no support for IPv6 wildcard entries yet.
I tried the following. It occurred no error but it did not work.
`smcroute -a eth0 :: ff08::7777 eth1 eth2`

Please add support for it like it is possible with IPv4:
`smcroute -a eth0 0.0.0.0 225.1.2.3 eth1 eth2`

**Comment by troglobit** [comment]
That is correct, (*,G) routes for IPv6 is not yet supported.

I have no means at the moment to develop or test this myself, care to give it a go yourself?

**Comment by bt-jo** [comment]
i've checked about (*,G) entry with linux kernel 4.4. and i could use (*.G) route using below :
smcroutectl -a eth0 :: FE05::158 eth0 bt0    -> works
smcroutectl -a eth0 :: FE05::158 bt0            -> it didn't working
(inbound interface : eth0 / outbout interface : bt0)

i'd like to know it is correct behavior. or is there any issue when i use this method ?

**Comment by troglobit** [comment]
@bt-jo My *"IPv6-fu"* is quite weak, but that shouldn't work.  There's no code to support it currently in `smcrouted`.  Also, the current code on the `master` branch is under refactoring, so please use a [released version](https://github.com/troglobit/smcroute/releases) in the meantime.

**Comment by bt-jo** [comment]
Thanks for your response.
I already know that smcrouted doesn't support it. i think smcrouted is management tool to support multicat routing. actually, multicast forwarding is role of kernel(such as ip6mr.c). so i checked kernal, i think kernel could support ipv6 (*,G) route if we add appropriate entry. for example, if there is no matched cache, then ip6_mr_input() function will call ip6mr_cache_find_any() to find  (*,G) entry. 
especially i added eth0 interface as outbound interface even if it is inbound interface on above example to work routing. i've tested it and it works well. i don't understand fully about this, but  kernel code below will be helpful.
https://patchwork.ozlabs.org/patch/213681/

Please correct me if my understanding is incorrect

**Comment by troglobit** [comment]
@bt-jo No, your understanding seem to be correct.

In the context of this issue the intention was to add support for `MRT6MSG_NOCACHE` MLD messages, similar to how `smcrouted` currently supports `IGMPMSG_NOCACHE` IGMP messages from the kernel.  The only reason that hasn't been done is my lack of time and understanding of IPv6.

However, your link to that Linux kernel patch by Nicolas Dichtel was *very interesting*, thank you!  I did not know of this kernel level support in Linux ... admittedly it was a while since I checked.

It would be interesting to play around with this! :smiley: :+1:

**Comment by troglobit** [comment]
I've just merged #129 from @hubertmis, so I'm closing this issue and welcome all of you to test the latest code on master and give feedback, in new issues.

Thank you all for your patience, and a huge thank you to @hubertmis for putting in all the hard workl! :star2:
