### ISSUE TITLE
Can't build on Centos 6

### ISSUE THREAD

**Issue by spyhunter99** [troglobit/smcroute#35]
autogen.sh works fine, no warnings
./configure work fines, no warnings
make errors out

smcroute.c:551: error: 'PACKAGE_URL' undeclared (first usage)

any idea on how to overcome this? I'm thinking I'm missing a dependency, but build dependencies aren't documented anywhere that I've found

**Comment by troglobit** [comment]
$ ./autogen.sh
    ...
    $ ./configure
    ...
    $ grep PACKAGE config.h
    #define PACKAGE "smcroute"
    #define PACKAGE_BUGREPORT "https://github.com/troglobit/smcroute/issues"
    #define PACKAGE_NAME "SMCRoute"
    #define PACKAGE_STRING "SMCRoute 2.2.0-dev"
    #define PACKAGE_TARNAME "smcroute"
    #define PACKAGE_URL "http://troglobit.com/smcroute.html"
    #define PACKAGE_VERSION "2.2.0-dev"

The configure script creates `config.h`, among other files, which `smcroute.c` includes.  I have no CentOS installation to try it out on, but ...

... only developer's should check out from GIT and use `autogen.sh` to create the configure script. If you're not aiming to contribute to the SMCRoute development you are better of with one of the released tarballs, e.g. https://github.com/troglobit/smcroute/releases/tag/2.1.0 -- [smcroute-2.1.0.tar.xz ](https://github.com/troglobit/smcroute/releases/download/2.1.0/smcroute-2.1.0.tar.xz)

With a released tarball you can call a pre-generated/safe configure script that should work even on older installations.

**Comment by spyhunter99** [comment]
Awesome, that did the trick. thanks!
