### ISSUE TITLE
Daemon error: Failed adding VIF for iface eth1: Cannot assign the requested address

### ISSUE THREAD

**Issue by spyhunter99** [troglobit/smcroute#36]
Not sure what's going on here. I have a centos machine with 2 network cards on 2 different networks and my goal is to use this computer as a router between the 2 networks (network A 192.168.1.0/24 and network B 10.1.1.0/24). The machines are connected via a simple unmanaged switch (there's no router in the picture besides the cenos machine with 2 nics). I've already setup and have basic routing (ping, udp, tcp, etc) between the 2 networks. 

I think smcroute is the right solution to route multicast traffic produced from network A to network B. (is it?)

iptables is cleared and stopped on all 3 machines in the picture

Long story short, my smcroute.conf look like this
````
phyint eth0 enable ttl-threshold 11
phyint eth1 enable ttl-threshold 11

mgroup from eth0 group 224.0.1.1
mroute from eth0 group 224.0.1.1 to eth1

mgroup from eth1 group 224.0.1.1
mroute from eth1 group 224.0.1.1 to eth0
````

After saving and starting the daemon, I don't get any errors to stdout. At this point multicast traffic is still not being routed. So I issued the following command
````
smcroute -j eth0 224.0.1.1
Sending commands....Daemon error: Failed adding VIF for iface eth1: Cannot assign the requested address
````
which is where i get the error message on the subject line.

Question, is smcroute the right tool for what I'm trying to accomplish? if so, what am I doing wrong (in terms the error message) and what else do i need to do in order to get this setup working?

**Comment by troglobit** [comment]
Usually UNIX daemons do not log to stdout/stderr, they log to syslog.  Check the syslog for more error messages first.

Next, why have you set up a ttl-threshold of 11, thresholds is for preventing routing of multicast with too low TTL.  The TTL must be > 1 for multicast to be routed, but you can scope into zones using the ttl-threshold setting, which is not what I think you want to do.

**Comment by troglobit** [comment]
But yes, from the few data points you've provided with your use-case, I do believe SMCRoute is what you are looking for.

Also, unlike unicast multicast does not have to be bi-directional. So if data is generated in network A and only destined for B, you only need one mroute rule.  You can see SMCRoute as a proxy, or repeater, of your multicast source in A, on B.

**Comment by troglobit** [comment]
Until I know more about why smcroute (the daemon) did not start properly (sylog), it is difficult to guess what is happening on your system.  It *could* be the ttl-threshold setting propagated to the VIF interface creation ... and on CentOS6 caused a problem. Dunno, need logs :)

**Comment by spyhunter99** [comment]
Thank you so much for the responses. Glad to know I'm on the right path.

The contents on /var/log/messages literally has the same error 
SMCRoute version 2.1.0
{timestamp} {hostname} Failed adding VIF for iface eth0: Cannot assign requested address
{timestamp} {hostname} Failed adding VIF for iface eth1: Cannot assign requested address
{timestamp} {hostname} Failed adding VIF for iface eth2: Cannot assign requested address
{timestamp} {hostname} Failed adding VIF for iface eth0: Cannot assign requested address
{timestamp} {hostname} Failed adding VIF for iface eth1: Cannot assign requested address

I'll keep digging to find more information.

So I'm clear, you want me to change
````
phyint eth0 enable ttl-threshold 11
phyint eth1 enable ttl-threshold 11
````
to
````
phyint eth0 enable
phyint eth1 enable
````

or to
````
phyint eth0 enable ttl-threshold 1
phyint eth1 enable ttl-threshold 1
````

**Comment by spyhunter99** [comment]
Adding some more context. eth0 and eth1 have no default gateway. eth2 has a default gateway that routes to the internet. 

when i disabled eth2 then bounced smcroute, i got some different log output. If this case, there would be no gateway from the machine running smcroute and no physical router.

````
SMCRoute version 2.1.0
{timestamp} {hostname} Failed adding VIF for iface eth0: Cannot assign requested address
{timestamp} {hostname} Failed adding VIF for iface eth1: Cannot assign requested address
{timestamp} {hostname} Failed adding VIF for iface eth2: Cannot assign requested address
{timestamp} {hostname} Failed adding VIF for iface eth0: Cannot assign requested address
{timestamp} {hostname} Failed adding VIF for iface eth1: Cannot assign requested address
{timestamp} {hostname} ADD MEMBERSHIP failed: No such device
{timestamp} {hostname} ADD MEMBERSHIP failed: No such device
````


A bidirection multicast setup is exactly what I'm looking for. I'm also setting up dummy net on the machine running smc. 

I can run `tcpdump -i eth1 host 224.0.1.1` on the smc box, I do see messages being delivered from network A. 0 packets dropped by the kernel, 10 packets captured, 10 packets received by filter

**Comment by spyhunter99** [comment]
More experimentation. I reenabled eth2 (the one with internet access) restarted smcroute then ran
this is network A
```
smcroute -j eth0 224.0.1.1 
> Sending command(s) ... Daemon error : ADD MEMBERSHIP failed: No such device
````
this is network B
````
smcroute -j eth1 224.0.1.1 
> Sending command(s) ... Daemon error : ADD MEMBERSHIP failed: No such device
````

this is the internet facing nic
````
smcroute -j eth2 224.0.1.1 
> Sending command(s) ... OK!
````

Using smcoute to join a group apparently only works on networks with a gateway and with a physical layer 3 router attached. Is this an accurate statement?

To add some more clarity to what I'm trying to do...I'm attempting to build a small isolated (no internet) network that forces routing through the centos box which has a bunch of network cards. Using dummynet on the centos box, I can then apply all kinds of network profiles (latency, packet loss, etc) to test applications running on network A and network B over simulated network conditions. I can do this right now, for everything BUT multicast. I've only been able to get multicast work (at all) on networks with an actual router on it. Unfortunately this doesn't work for me as I need to be able to inject delay and packet loss, etc. That said, am I still on the right path with using smcroute?

**Comment by troglobit** [comment]
Let me try to explain a bit about multicast routing in general, and SMCRoute in particular.

Multicast routing is performed by the kernel, it doesn't really need much to perform this task, but it's a little bit different from unicast routing, for one it doesn't use the same routing table.  A multicast route consists of a multicast group, a source/sender IP with an inbound interface (VIF, more on that below), and one or more outbound interfaces to route the multcast to. That's it, no default route is queried or anything. Data in -- data out.

However, on layer 2 (or 2.5) the broadcast effects of multicast can be controlled by protocols like IGMP (IPv4) or MLD (IPv6). For a multicast sender to start sending multicast in the general direction of a router it usually requires an IGMP join, which is also what IGMP/MLD aware switches snoop up and use to limit what ports on the switch receive each multicast group. (It's a bit more to it than that, there is also an IGMP querier, which usually is the router, that all multicast must be forwarded to, unconditionally ...)  If you control the sender, or have only stupid unmanaged switches, or you know the sender always sends, then you do not need `smcroute -j` or `mgroup` (which are the same) on that network.

The IGMP joins are also handled by the kernel. Depending on the IGMP protocol version negotiated on the LAN they can be sent to any group on 224.0.0.0/4, these days all joins go to 224.0.0.22 (IGMPv3).  If a default route is set the kernel will send joins on that outbound interface, but you can also set up a net route for 224.0.0.0/4. _If you at all need IGMP joins?_ I know too little about your network to give you any recommendations here.

You mention bidirectional multicast. In the world of multicast that concept doesn't really exist. You can only have one sender per group, if you have more than one sender to the same grou it is more or less assumed they are streaming the same data.  If both networks A and B want multicast group M and the sender S is located on A, then IGMP/MLD will handle distribution of M on A and your router R can route M to B.  No need to do the reverse (M --> A) since M is already available on A.  So, you should not have two rules like you have in the short snippet I've seen of your .conf file.

Now, what is a VIF?  Multicast routing does not use your regular interfaces but creates _virtual interfaces_ that multicast routes then operate on.  It may sound a bit weird, and trust me it is.  If these VIF's cannot be created (as indicated by the three first log messages), then multicast routing will not work. I have no idea why it doesn't work for you, my guess was the `ttl-threshold` setting you had set, maybe that new feature, introduced in v2.1.0, somehow doesn't work on the CentOS 6 kernel, I don't even know what kernel version is used ... maybe downgrading to v2.0.0 would work better for you, or stripping down the configuration file.

    # Simple stripped-down smcroute.conf
    mroute from eth1 group 224.0.1.1 to eth0

That's it.

- No `mgroup` (as long as you can see 224.0.1.1 on eth1 without a join),
- No `phyint enable` or `ttl-threshold` (unless you disable ALL interfaces with the command line switch -N when starting the daemon)

I hope this makes things a little bit clearer for you! Multicast is a bit special compared to unicast, so it takes a lot of reading up on to get the hang of.

**Comment by spyhunter99** [comment]
Wow thanks for the explanation. When I meant bidirectional, is that I will have multiple apps transmitting and receiving on the same multicast ip/port, some on network A and some on B. 

The current setup is centos6 with kernel 2.6.32-573.e16.x86_64. I made the edits to scmroute.conf and restarted everything. Still getting the VIF message. I can look into getting an older version of the kernel if you think it would help. There may be kernel setting i can tweak to get things moving. The problem is i'm not sure what the problem is. It's possible that IGMP packets are being received but not delivered to user space. tcpdump dumps shows the receipt of 3 messages on 224.0.0.22 which were delivered to both network A and B nics on the routing box.

As far as IGMP, I know little about it too. There's good old ping and some magic Join/Leave messages related to multicast networking that somehow notify something on the network to forward packets to the interested parties. I'm also running all 3 machines as virtual box VMs at the moment, which connects them all together via some kind of virtual switch.

**Comment by spyhunter99** [comment]
I just installed smcroute 2.0.0. I no longer get the VIF error message.

I also did some additional experimentation with tcpdump. Currently I have a simple java app transmitting multicast traffic "hello world" on Network A. I just ran tcpdump on Network B and it's confirming delivery of the multicast traffic there. So the problem may be specific to that machine and/or the app that supposed to join the group and receive the traffic. Progress!

**Comment by troglobit** [comment]
That's a very old kernel. SMCRoute v2.1.0 relies on having at least 2.6.33 these days, there is no testing done on such old software. 

Like I mentioned above, it is more or less assumed that the source of a multicast group only exists in one place. So you will definitely run into problems if the source sometimes is on A and other times on B, you will run into "interesting" problems if both sources transmit at the same time. This has nothing to do with IGMP, it is just a limitation of multicast, the UNIX multicast routing stack and how SMCRoute operates -- it is a _static_ multicast routing daemon.  You may need to look into _dynamic_ multcast routing daemons, like pimd or mrouted, which can handle dynamic changes like that.  The latter two also take over the role as IGMP queriers from the kernel.

For future reference, when reporting a bug/problem with any piece of software it is good to start out with complete configuration files, system information, including logs, and in the case of networking software, the network topology. Multicast and virtual machines do not usually play nice together, this is such a common problem I even have an [FAQ](http://troglobit.com/multicast-howto.html) about it.

**Comment by spyhunter99** [comment]
Thanks for the info (again). I updated the smcroute to a newer centos version. Now running kernel 3.10.0-327.18.2.e17.x86_64 with smcroute 2.1.0. It starts without any error messages. Again, I can route unicast without a problem. I can see packets coming in and out of the smcroute machine.

The machine on Network A is doing the transmit. Machine on Network B is set to receive. 

Using tcpdump on machine A, i can see the outbound traffic.
On the smcroute machine, I can see the traffic coming in and going out. netstat -g shows that we're joined to 224.0.0.1 (note that our target multicast group is 224.0.1.1)
On machine B, using tcpdump I see the mutlicast traffic coming in. netstat -g shows that we're joined. Unfortunately the java app isn't registering the traffic. After some debugging and swearing, it looks like everything it working! thanks for the help. Now if i can just get dummynet to affect the traffic...

**Comment by troglobit** [comment]
- Did you read my FAQ? 
- Did you check the TTL of the multicast traffic?

**Comment by spyhunter99** [comment]
I'm good, the packets are being delivered. I've set the TTL to 64 and yes i've read the faq. The part that caught my eye was this 

````
The routing daemons pimd/mrouted/smcroute only manipulate the multicast routing table(s) of the operaring system’s kernel.
````

Is there a tool or command to print out the multicast routing table?

**Comment by troglobit** [comment]
Try

    cat /proc/net/ip_mr_cache

or

    ip mroute

The mapped VIF's can be listed with 

    cat /proc/net/ip_mr_vif

**Comment by spyhunter99** [comment]
Strange, all 3 commands had no output aside from the table column headers on both the smcroute machine, and machines A and B.

**Comment by troglobit** [comment]
If `/proc/net/ip_mr_vif` doesn't list any interfaces then the SMCRoute daemon hasn't started properly.

**Comment by spyhunter99** [comment]
Ahh my mistake, I had Node A and B on the same vlan. Once I changed them to separate vlans and restart mrouted, the above commands starting displaying stats per nic. I can still send unicast between the machines, however multicast routing stopped at this point. At the router (box with smcroute) I see packets coming in via `cat /proc/net/ip_mr_vif` and tcpdump but nothing outbound.

`ip mroute' shows

````
(172.1.1.2, 224.0.1.1)           Iif: eth0       Oifs: eth1 
````
cat /etc/smcroute.conf 
````
mroute from eth1 group 224.0.1.1 to eth0
mroute from eth0 group 224.0.1.1 to eth1 
````

I also tried adding the groups via 'smcroute -a', no change.

````
cat /proc/net/ip_mr_vif
Interface      BytesIn  PktsIn  BytesOut PktsOut Flags Local    Remote
 0 eth0          11560     289         0       0 00000 010101AC 00000000
 1 eth1              0       0         0       0 00000 0101010A 00000000
 2 eth2              0       0         0       0 00000 0A01A8C0 00000000
````

````
cat /proc/net/ip_mr_cache
Group    Origin   Iif     Pkts    Bytes    Wrong Oifs
010100E0 020101AC 0        304    12160        0  1:1  
````

Netstat doesn't report joining any groups, not sure if this is a problem per say...
````
netstat -gn
IPv6/IPv4 Group Memberships
Interface       RefCnt Group
--------------- ------ ---------------------
lo              1      224.0.0.1
eth0            1      224.0.0.1
eth1            1      224.0.0.1
eth2            1      224.0.0.1
lo              1      ff02::1
eth0            1      ff02::1:ff41:cf79
eth0            1      ff02::1
eth1            1      ff02::1:ff97:cd0
eth1            1      ff02::1
eth2            1      ff02::1:fffd:f6d4
eth2            1      ff02::1
````

Any idea where i need to go from here?

**Comment by troglobit** [comment]
Check the TTL of the inbound stream on eth0 to 224.0.1.1 ... that _remains_ the most common error.

**Comment by spyhunter99** [comment]
ok great news, i was able to resolve all the issues on bare metal. For future readers
centos6 works with smcroute 2.0.0

these are needed since i'm using centos as a software router
/etc/sysctl.conf

````
net.ipv4.conf.default.rp_filter=2
net.ipv4.ip_forward=1
````

/etc/smcroute.conf
````
mroute from eth1 group 224.0.1.1 to eth2
````

start smcroute 

````
./smcroute -d
````


`netstat -gn` will not show multicast group membership unless you explicit need to join the that group for some reason, however the routing still works.

The final issue i have had was that when i add a pipeline for dummynet, smc stops routing traffic. In fact, all traffic was blocked. Turns out that dummynet behaves differently when the computer is configured as a router. 

`ipfw add pipe 1 ip from any to any`
no multicast routing
`ipfw flush`
multicast routing is restored

the solution was to add an explicit allow rule for dummynet, which is also a firewall.
`ipfw add 100 allow all from any to any`

In my case I had to play around with the number to get it equal to the rule sets for traffic shaping. Not sure why but that did the trick.

Thanks again for your help!

**Comment by troglobit** [comment]
Great news, good luck! :smiley:

**Comment by grantcurell** [comment]
> Let me try to explain a bit about multicast routing in general, and SMCRoute in particular.
> 
> Multicast routing is performed by the kernel, it doesn't really need much to perform this task, but it's a little bit different from unicast routing, for one it doesn't use the same routing table. A multicast route consists of a multicast group, a source/sender IP with an inbound interface (VIF, more on that below), and one or more outbound interfaces to route the multcast to. That's it, no default route is queried or anything. Data in -- data out.
> 
> However, on layer 2 (or 2.5) the broadcast effects of multicast can be controlled by protocols like IGMP (IPv4) or MLD (IPv6). For a multicast sender to start sending multicast in the general direction of a router it usually requires an IGMP join, which is also what IGMP/MLD aware switches snoop up and use to limit what ports on the switch receive each multicast group. (It's a bit more to it than that, there is also an IGMP querier, which usually is the router, that all multicast must be forwarded to, unconditionally ...) If you control the sender, or have only stupid unmanaged switches, or you know the sender always sends, then you do not need `smcroute -j` or `mgroup` (which are the same) on that network.
> 
> The IGMP joins are also handled by the kernel. Depending on the IGMP protocol version negotiated on the LAN they can be sent to any group on 224.0.0.0/4, these days all joins go to 224.0.0.22 (IGMPv3). If a default route is set the kernel will send joins on that outbound interface, but you can also set up a net route for 224.0.0.0/4. _If you at all need IGMP joins?_ I know too little about your network to give you any recommendations here.
> 
> You mention bidirectional multicast. In the world of multicast that concept doesn't really exist. You can only have one sender per group, if you have more than one sender to the same grou it is more or less assumed they are streaming the same data. If both networks A and B want multicast group M and the sender S is located on A, then IGMP/MLD will handle distribution of M on A and your router R can route M to B. No need to do the reverse (M --> A) since M is already available on A. So, you should not have two rules like you have in the short snippet I've seen of your .conf file.
> 
> Now, what is a VIF? Multicast routing does not use your regular interfaces but creates _virtual interfaces_ that multicast routes then operate on. It may sound a bit weird, and trust me it is. If these VIF's cannot be created (as indicated by the three first log messages), then multicast routing will not work. I have no idea why it doesn't work for you, my guess was the `ttl-threshold` setting you had set, maybe that new feature, introduced in v2.1.0, somehow doesn't work on the CentOS 6 kernel, I don't even know what kernel version is used ... maybe downgrading to v2.0.0 would work better for you, or stripping down the configuration file.
> 
> ```
> # Simple stripped-down smcroute.conf
> mroute from eth1 group 224.0.1.1 to eth0
> ```
> 
> That's it.
> 
> * No `mgroup` (as long as you can see 224.0.1.1 on eth1 without a join),
> * No `phyint enable` or `ttl-threshold` (unless you disable ALL interfaces with the command line switch -N when starting the daemon)
> 
> I hope this makes things a little bit clearer for you! Multicast is a bit special compared to unicast, so it takes a lot of reading up on to get the hang of.



> Let me try to explain a bit about multicast routing in general, and SMCRoute in particular.
> 
> Multicast routing is performed by the kernel, it doesn't really need much to perform this task, but it's a little bit different from unicast routing, for one it doesn't use the same routing table. A multicast route consists of a multicast group, a source/sender IP with an inbound interface (VIF, more on that below), and one or more outbound interfaces to route the multcast to. That's it, no default route is queried or anything. Data in -- data out.
> 
> However, on layer 2 (or 2.5) the broadcast effects of multicast can be controlled by protocols like IGMP (IPv4) or MLD (IPv6). For a multicast sender to start sending multicast in the general direction of a router it usually requires an IGMP join, which is also what IGMP/MLD aware switches snoop up and use to limit what ports on the switch receive each multicast group. (It's a bit more to it than that, there is also an IGMP querier, which usually is the router, that all multicast must be forwarded to, unconditionally ...) If you control the sender, or have only stupid unmanaged switches, or you know the sender always sends, then you do not need `smcroute -j` or `mgroup` (which are the same) on that network.
> 
> The IGMP joins are also handled by the kernel. Depending on the IGMP protocol version negotiated on the LAN they can be sent to any group on 224.0.0.0/4, these days all joins go to 224.0.0.22 (IGMPv3). If a default route is set the kernel will send joins on that outbound interface, but you can also set up a net route for 224.0.0.0/4. _If you at all need IGMP joins?_ I know too little about your network to give you any recommendations here.
> 
> You mention bidirectional multicast. In the world of multicast that concept doesn't really exist. You can only have one sender per group, if you have more than one sender to the same grou it is more or less assumed they are streaming the same data. If both networks A and B want multicast group M and the sender S is located on A, then IGMP/MLD will handle distribution of M on A and your router R can route M to B. No need to do the reverse (M --> A) since M is already available on A. So, you should not have two rules like you have in the short snippet I've seen of your .conf file.
> 
> Now, what is a VIF? Multicast routing does not use your regular interfaces but creates _virtual interfaces_ that multicast routes then operate on. It may sound a bit weird, and trust me it is. If these VIF's cannot be created (as indicated by the three first log messages), then multicast routing will not work. I have no idea why it doesn't work for you, my guess was the `ttl-threshold` setting you had set, maybe that new feature, introduced in v2.1.0, somehow doesn't work on the CentOS 6 kernel, I don't even know what kernel version is used ... maybe downgrading to v2.0.0 would work better for you, or stripping down the configuration file.
> 
> ```
> # Simple stripped-down smcroute.conf
> mroute from eth1 group 224.0.1.1 to eth0
> ```
> 
> That's it.
> 
> * No `mgroup` (as long as you can see 224.0.1.1 on eth1 without a join),
> * No `phyint enable` or `ttl-threshold` (unless you disable ALL interfaces with the command line switch -N when starting the daemon)
> 
> I hope this makes things a little bit clearer for you! Multicast is a bit special compared to unicast, so it takes a lot of reading up on to get the hang of.

@troglobit -I'm necroing this thread hardcore, I just want you to know that explanation was really helpful 5 years later
