### ISSUE TITLE
Source Specific Multicast  support

### ISSUE THREAD

**Issue by yarrr-ru** [troglobit/smcroute#42]
Hello,

Is anyone need "Source Specific Multicast" (IP_ADD_SOURCE_MEMBERSHIP/IP_DROP_SOURCE_MEMBERSHIP) support for smcroute?

I have simple diff for myself: https://github.com/yarrr-ru/smcroute/commit/c52f0c7bafbf49e92b1aa274b30314ce742c3cc1

But I can clean up code, add ipv6 support and make pull request if anyone except me need this.

**Comment by troglobit** [comment]
Neat! :+1: 

From my point of view I think documentation and conf-file support would be more interesting, rather than IPv6 support -- if your time is limited, that is :smiley:

**Comment by yarrr-ru** [comment]
No limit at all, thanks for reminder about doc :)
I'll try to make pull request soon.

**Comment by troglobit** [comment]
No rush, awesome work btw! :smiley:

**Comment by yarrr-ru** [comment]
"soon" = almost 3 months :(
Pull request: https://github.com/troglobit/smcroute/pull/48

**Comment by troglobit** [comment]
No worries, I haven't exactly been a busy bee myself 😏

I'll have a look later this week. Cheers!
