### ISSUE TITLE
Add option to run daemon as user specified in configuration

### ISSUE THREAD

**Issue by remedi** [troglobit/smcroute#43]
smcroute daemon can be run without root using capability CAP_NET_ADMIN. This capability enables the thread (among other networking related things) to add and remove multicast routes. This reduces the potential security risks involved in running the daemon with elevated privileges.

The syntax is as follows: /etc/smcroute.conf
user USERNAME

smcroute starts with root privileges. After initial startup procedure it will try to change the GID, UID and supplementary groups while preserving CAP_NET_ADMIN capability. It assumes that the target user exists, otherwise it will just print error message and continue running the daemon as root.

All capability and identity related functions that I used are cross-platform, and most seem to be POSIX compliant. Compiling requires linking libcap. If you are interested in this feature, I can fork and commit it.

**Comment by remedi** [comment]
This would also require updating the documentation. The feature should probably be behind configurable preprocessor flag?

**Comment by troglobit** [comment]
Sounds awesome, of course we're interested! =)

At least some basic documentation would be really useful if you could add, I can polish it up later if needed.  

Maybe a runtime option is more preferable, like this?

     -p, --drop-privs=USER[:GROUP]      Drop privileges after start to USER:GROUP

Dunno ...

**Comment by remedi** [comment]
Yes, that makes sense. I can edit my implementation to take the target user and group as command-line arguments. I can also edit the command-line help and README to reflect the changes.

**Comment by troglobit** [comment]
Great! :)
