### ISSUE TITLE
No buffer space error

### ISSUE THREAD

**Issue by dsuded** [troglobit/smcroute#46]
Hello,

When I try to add more than 20 streams, I get this error:
smcroute[41855]: ADD MEMBERSHIP failed. Error 105: No buffer space available

Is that a limit with the daemon that is written in manual, or do I need to tune some protocol parameters?
Any help or suggestion is greatly appreciated.

Thanks

**Comment by troglobit** [comment]
It would help to see your config file, or an example thereof at lest.

I suspect you are using the `mgroup` command, because that is limited to 20 groups.  This is also mentioned in the documentation as a kernel per-socket limitation.  See the man page for more help.

**Comment by dsuded** [comment]
Hi,

I don't have any config file present. I used command smcroute -j eth42 239.123.173.3 and so forth for every stream I wanted to monitor but when I wanted to hit 21st it showed up mentioned error. I have 1 Gbit NIC so that shouldn't be the issue.

**Comment by troglobit** [comment]
The -j command only sends a layer-2 join for the multicast group ... sorry, but I have to ask, what problem are you trying to solve?

**Comment by dsuded** [comment]
It's solved. I had to increase net.ipv4.igmp_max_memberships from default 20. Basically what I'm trying to achieve is to monitor 100+ streams on a dedicated hardware for quality inspection.
Thank you for help.

**Comment by troglobit** [comment]
There are better tools for that. Check out my [mcjoin](https://github.com/troglobit/mcjoin) project, awesome for testing like that.

OK, closing issue :-)
