### ISSUE TITLE
smcroute on arm64

### ISSUE THREAD

**Issue by meteorza** [troglobit/smcroute#47]
Hi

Trying to get smcroute to work on 64bit ARM box. I have used it on 32bit ARM before (ver 2.0.0) without any problems.

`3.14.77 #2 SMP PREEMPT Sat Sep 24 07:18:38 UTC 2016 aarch64 aarch64 aarch64 GNU/Linux`

I did install and compile latest build:

```
smcroute -v
SMCRoute version 2.2-rc1 build
```

I do run daemon without any errors, but it seems the daemon never starts 
smcroute -d

When I try to kill the running kernel or add routes, I get:

`Daemon not running: Connection refused`

IP multicast is enabled in kernel, here is snippet from defconfig used to build kernel:
```
CONFIG_IP_MULTICAST=y
CONFIG_IP_ADVANCED_ROUTER=y
```

Just want to confirm that it should work in ARM64 before spending too much time on troubleshooting.

**Comment by troglobit** [comment]
Well, it should work, but I've never tested it personally. Would be
interesting to see why ...

**Comment by meteorza** [comment]
My journalctl -f in Ubuntu on the box shows:

Sep 24 10:13:37 wetek smcroute[8454]: SMCRoute version 2.2-rc1 build
Sep 24 10:13:37 wetek smcroute[8454]: Failed initializing IPv4 multicast routing API: Protocol not available

Does this mean there is something disabled in kernel then?

**Comment by troglobit** [comment]
Looks it. Try enabling the PIM stuff … I should update the README with
better info on this. Sorry

**Comment by meteorza** [comment]
Yes, that was it, enabled the PIM stuff in kernel and it is working now. Thank you.

**Comment by troglobit** [comment]
Awesome! ☺👍
