### ISSUE TITLE
Failed call to select() in server_loop() error when activating cache life time feature

### ISSUE THREAD

**Issue by mellowcandle** [troglobit/smcroute#51]
After the first flush, I get continuous warn in the log file.
I added a debug print just before calling select. the problem is with the timeout parameter.
`smclog(LOG_WARNING, "Calling select() with max_fd_num = %u, tmo: sec %u usec %u", max_fd_num+1, tmo->tv_sec, tmo->tv_usec);`

> Calling select() with max_fd_num = 6, tmo: sec 10 usec 0
> Cache timeout, flushing all (*,G) routes!
> Calling select() with max_fd_num = 6, tmo: sec 10 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 8 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 7 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 6 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 6 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 6 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 0 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 0 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 0 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 0 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 0 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 0 usec 0
> Calling select() with max_fd_num = 6, tmo: sec 0 usec 0
> ...
> Calling select() with max_fd_num = 6, tmo: sec 4294967295 usec 0
> Failed call to select() in server_loop(): Invalid argument
> Calling select() with max_fd_num = 6, tmo: sec 4294967295 usec 0
> Failed call to select() in server_loop(): Invalid argument
> Calling select() with max_fd_num = 6, tmo: sec 4294967295 usec 0
> Failed call to select() in server_loop(): Invalid argument
> Calling select() with max_fd_num = 6, tmo: sec 4294967295 usec 0
> Failed call to select() in server_loop(): Invalid argument
> Calling select() with max_fd_num = 6, tmo: sec 4294967295 usec 0
> Failed call to select() in server_loop(): Invalid argument
> Calling select() with max_fd_num = 6, tmo: sec 4294967295 usec 0
> Failed call to select() in server_loop(): Invalid argument
> Calling select() with max_fd_num = 6, tmo: sec 4294967295 usec 0

**Comment by mellowcandle** [comment]
The test was ran without any multicast packets sent / received.

**Comment by troglobit** [comment]
Hmm, that's no good.  Thank you for trying it out and reporting!

**Comment by troglobit** [comment]
@mellowcandle I've pushed a fix in 708c68e for this issue.  If everything works fine on your end, I can release v2.2.2 tonight (CET).

**Comment by troglobit** [comment]
There, v2.2.2 released! :smiley: :tada: 

https://github.com/troglobit/smcroute/releases/tag/2.2.2
