### ISSUE TITLE
smcroute doesn't run on the foreground.

### ISSUE THREAD

**Issue by crocket** [troglobit/smcroute#54]
On ArchLinux and OpenWrt, `smcroute -n` silently exits.

`smcroute -n -D` prints nothing to stdout. `journalctl` doesn't show anything related to `smcroute` after executing `smcroute -n -D`.

**Comment by troglobit** [comment]
SMCRoute has two operating modes: server and cllient.  The server can start and run without ever having to use the client, using a `smcroute.conf` file:

    smcroute -d

With the `-n` argument to `-d` SMCRoute should run in the foreground.

I don't know what you expected with `-D`, but what likely happened, and what I can make clearer, is that SMCRoute entered its client mode but got no commands.

**Comment by crocket** [comment]
`smcroute -n -d` works fine.

**Comment by troglobit** [comment]
Good to hear :-)
