### ISSUE TITLE
show routes prints packet/byte counts as signed values

### ISSUE THREAD

**Issue by bshankstd** [troglobit/smcroute#77]
`smcroutectl show routes` prints the `unsigned long` packet/byte counts as signed values, which will print as negative if they're large enough. I think the bug is using `%ld` rather than `%lu` in [mroute.c L1136](https://github.com/troglobit/smcroute/blob/4b19f2280beebaa1605e0eb847299b095957a957/src/mroute.c#L1136)

```
# smcroutectl show routes
ROUTE (S,G)                        INBOUND          PACKETS    BYTES  OUTBOUND                                                                                                       
(172.24.100.221, 239.192.1.40)     eth0             18308031 -11638101
```

**Comment by troglobit** [comment]
Thanks for the bug report!  Also fixed the width of the format specifier.
