### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [troglobit/smcroute#83]
I would like to point out that identifiers like “[`__pidfile_path`](https://github.com/troglobit/smcroute/blob/025a5d041827371606e2f982c36b6f1194c0714b/src/pidfile.c#L52 "Update candidate")” and “[`_Q_INVALIDATE`](https://github.com/troglobit/smcroute/blob/424b921effebc092ed2a3030d9e95fa9393d8cf5/src/queue.h#L82 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by troglobit** [comment]
The pidfile handling and queue.h is from *BSD. I'd rather keep the as much as possible in sync with the original upstream versions. Admittedly I've modified pidfile() to handle updating mtime if called multiple times.

Curious, why is this an issue for you? I would agree with you if this was a library, by SMCRoute is a stand-alone program.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
