### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [troglobit/smcroute#84]
Would you like to add more error handling for return values from functions like the following?
- [fputs](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream") ⇒ [ipc_command](https://github.com/troglobit/smcroute/blob/be62f42e309bd1c6c899f9ed048aab9f25d5ae80/src/smcroutectl.c#L195)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action") ⇒ [signal_init](https://github.com/troglobit/smcroute/blob/9b93641bd830bff952cd45ac5f35d568040c28b7/src/smcrouted.c#L127)

**Comment by troglobit** [comment]
If fputs(buf, stdout) fails, what do you propose one should do with the error? Sure, one could return an error code from smcroutectl, but how likely is it to fail?

sigaction() only fails if we have serious memory problem, of if you try to set up an action for SIGKILL or SIGSTOP, which we don't. If the former is the case we are likely in deep trouble anyway.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by troglobit** [comment]
Pull requests welcome.
