### ISSUE TITLE
Document how to use iptables TTL target

### ISSUE THREAD

**Issue by nihilus** [troglobit/smcroute#86]
Some thing like this:
``
 iptables -t mangle -A PREROUTING -i eth0 -d 239.255.255.250 -j TTL --ttl-inc 1
``

**Comment by bombadil** [comment]
Fixing the TTL by intermediate routers is dangerous and can cause loops flooding your network more easily than necessary.

You are not describing properly what problem this is trying to solve. Why is the sender using a TTL that would make this dangerous hack necessary?

**Comment by nihilus** [comment]
If that is an is an issue then you have more than that issue on your network. Any sane OS use a TTL of 1 for multicast traffic on the same subnet, hence you need to increase it ior else the packets will get discarded by the router and not forwarded.

**Comment by troglobit** [comment]
I'm a bit hesitant to put something like this in the official SMCRoute documentation.  Like @bombadil says, adjusting the TTL like this can lead to unintended consequences, and there's also usually thought behind a TTL=1 in a protocol.  OK, sane operating systems default to a TTL=1 for multicast sockets, but that's mostly to counter the broadcast nature of multicast.  For multicast based protocols, e.g. mDNS and SSDP, there is usually a great deal of thought behind the TTL value in the protocol.  In this case the protocols are intended to be link-local only, so routing them was never the intention of the protocol authors. If the need arises, in most cases it is better to instead use an L2 tunnel and bridge with a remote/neighboring LAN.

Also, this iptables trick is mentioned in my [Multicast FAQ](http://troglobit.com/howto/multicast/).

**Comment by bombadil** [comment]
@nihulus Usually the sender is supposed to set a TTL greater than 1 so that routers don't need to fiddle with it.

Still you didn't describe your problem, so I don't know whether that is an appropriate solution.

**Comment by nihilus** [comment]
@bombadil As one can deduce from the multicast IP it is for routing SSDP between two interfaces on the same host/router.

**Comment by bombadil** [comment]
Thanks, I prefer to avoid misunderstandings by not guessing (or deducting) what others actually want if they don't state it explicitly. Sorry for asking.
