### ISSUE TITLE
Source-specific routes in smcroute are not consistent with kernel mfc

### ISSUE THREAD

**Issue by nekrasov-pavel** [troglobit/smcroute#89]
Kernel multicast routes are identified by pair (source_address, group), but routes in smcroute are identified by (in_vif, source_address, group).
E.g., we add route with smcroutectl:
**smcroutectl add eth0 10.1.1.1 239.1.1.1 eth1**. 
Now **smcroutectl show** and **ip mroute** show the same routes:
(10.1.1.1, 239.1.1.1) Iif: eth0 Oifs: ext0.
 We add another route with smcroutectl:
**smcroutectl add eth1 10.1.1.1 239.1.1.1 eth0**.
Now **smcroutectl show** dispays two routes (previous and new), but kernel **ip mroute** shows only new route.

**Comment by troglobit** [comment]
Kernel multicast routes are also identified with inbound VIF, that's what the `Iif:` signifies.

I believe you've found a bug with SMCRoute, most likely in the internal list management code used to keep track of "dynamic" routes.  I'll have a look at it later today.

**Comment by nekrasov-pavel** [comment]
Ok, thanks! 
You can try the example I've considered. Also you can look at kernel code (http://elixir.free-electrons.com/linux/latest/source/net/ipv4/ipmr.c#L1531) and see that for MRT_ADD_MFC and MRT_DEL_MFC: parent=-1, which is later used in cache lookup ipmr_cache_find_parent (here http://elixir.free-electrons.com/linux/latest/source/net/ipv4/ipmr.c#L1277 and here http://elixir.free-electrons.com/linux/latest/source/net/ipv4/ipmr.c#L1277). In cache lookup procedure ipmr_cache_find_parent (http://elixir.free-electrons.com/linux/latest/source/net/ipv4/ipmr.c#L1050) if parent is -1, than only (mfc_origin, mfcc_mcastgrp) are used for identifying route. Actually, input vif (mfcc_parent) is used only for MRT_ADD_MFC_PROXY and MRT_DEL_MFC_PROXY signals.

**Comment by troglobit** [comment]
Sorry, but I'm pretty sure that's not the root cause here.  In multicast you can only have one (S,G) pair (per multicast routing table) in the kernel.  When a second (S,G) pair matching the first is loaded to the kernel the iif changes and the previous entry is lost, however the list in `smcrouted` likely does not handle this case (the old entry should be removed, that's the bug).  So the resulting case you see with `ip mroute` is correct.

**Comment by nekrasov-pavel** [comment]
Yes, we are talking about the same thing :) 
`smcrouted` should remove the old entry in its lists to match with kernel routing table.

**Comment by troglobit** [comment]
OK, great! Always best to double-check before starting to make changes 😎

**Comment by troglobit** [comment]
Should be fixed in 0fa16cd, please reopen issue if you still have experience problems with this.
