### ISSUE TITLE
SIGHUP on unprivileged smcrouted does not work (as I expected)

### ISSUE THREAD

**Issue by mcpat** [troglobit/smcroute#90]
Sending a SIGHUP to the unprivileged smcrouted will clean up all resources properly.
But it will then fail to reacquire those because of the lack of permissions. Most significantly the daemon will not be able to re-create the IGMP socket.

I suggest to add some information about this to the documentation.

**Comment by mcpat** [comment]
I experimented a bit:
If one does not close the IGMP socket in mroute4_disable and reuse it later in mroute4_enable the daemon will again work as expected. Maybe this is a valid way to enable re-configuration of the unprivileged daemon!? - I do not know all the consequences.
In my case it seems sufficient so I will prepare a patch for it.

**Comment by troglobit** [comment]
Good catch! It should work, and this may require a bit of a redesign of the priv. sep. handling. For completeness, I'm assuming you run the latest version from GitHub?

We close the routing sockets because doing so will flush all routes from the kernel. If we keep them open we must not have any bugs in the cleanup/removal of routes ...

**Comment by mcpat** [comment]
Yes, the latest release version.
From what I see in the kernel sources, the MRT_DONE used in mroute4_disable should flush the routes and tables associated with the socket. So I would expect, that the state after MRT_DONE should be the same as creating a new socket afresh (before MRT_INIT). I must confess, that I am not that deep down in multicast routing so I could still be completely wrong here.
From what I see in my tests (I only setup two static routes for one group between two interfaces) it works so far. Sadly, I am not able to extend my testing any further due to time limitation.

**Comment by troglobit** [comment]
Nice, I had completely forgotten about `MRT_DONE`! In that case, if you have the time, please go ahead and prepare a patch. We'll help out with audit and testing :smiley::+1:

**Comment by mcpat** [comment]
See https://github.com/mcpat/smcroute/commit/3550cc7ab6155c6ddbf2281a0896ec87c5e9986c

**Comment by troglobit** [comment]
@mcpat Looks good!  Just a few minor coding-style issues (`if(foo)` instead of `if (foo)`), but those I can clean up myself when you submit a pull request.
