### ISSUE TITLE
Changing the source IP

### ISSUE THREAD

**Issue by ChrisAbela** [troglobit/smcroute#92]
I have a simple application with smcroute to route a multicast data stream from interface eth0 to eth1. It works fine, but my application requires specific source IP which does not match the source IP (at eth0) and I am noting that the the source IP of the data source is streamed out of eth1. Is it possible to change the source IP according to the source IP of eth1 (or some other means)?

**Comment by troglobit** [comment]
Not using SMCRoute, it only manages the multicast routing table(s) of the kernel.  However, the kernel (depending on your flavor of UNIX) has several mechanisms for this, search for SNAT.

**Comment by ChrisAbela** [comment]
I'l try that.
Thank You.

**Comment by troglobit** [comment]
No problem, good luck! :)

**Comment by ChrisAbela** [comment]
For the sake of anyone looking for a similar solution; this worked for me:

iptables -t nat -A POSTROUTING -o eth1 -j SNAT --to <new_source_address>

**Comment by troglobit** [comment]
Awesome, thanks for the follow-up! :+1:
