### ISSUE TITLE
Newest version is not available in Debian and Ubuntu

### ISSUE THREAD

**Issue by thedrow** [troglobit/smcroute#94]
It is very unfortunate that smcroute 2.4.0 is not available in Ubuntu 18.04 LTS.
smcroute 2.4.0 is also not available in Debian Sid.

Who do I need to talk to, to get the packages upgraded?

**Comment by troglobit** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846780

**Comment by troglobit** [comment]
Maybe @bombadil can comment on this, although I guess it's on the TODO list with lots of other pressing matters before it? :smiley:

**Comment by bombadil** [comment]
I am hearing you. Yeah, updating the Debian package is over due.

@troglobit, could you provide some guidance how any existing configuration for SMCRoute 2.0.0 needs to be re-written for 2.4.0?

**Comment by troglobit** [comment]
@bombadil There's a lot of changes, but mostly new features that don't break existing configuration files.  Here's my take on a terse summary, with highlights from the ChangeLog:

1. `mgroup` now take an optional `[source ADDRESS]` argument for SSM join
2. `phyint` is a new interface specific setting, meaning all interfaces can be disabled by default, and enable one by or, or be disabled one by one.  It also controls TTL scoping and the optional `[mrdisc]` feature to enable multicast router discovery ([RFC4286](https://tools.ietf.org/html/rfc4286)) 
3. `mroute` now take an optional `[/LEN]` argument to groups
4. `smcrouted` and `smcroutectl`, the split of `smcroute` into two entities

The most interesting feature IMO is the mrdisc support. It has the potential to greatly simplify deployments in setups where switches respect mrdisc messages and seamlessly forward multicast towards the SMCRoute router.

I've been auditing the .conf file and documentation a bit, so there will be a v2.4.1 out shortly.

**Comment by thedrow** [comment]
@bombadil Hi, Need any help?

**Comment by thedrow** [comment]
How? What do you need me to do?

**Comment by shotahino** [comment]
Gentle ping :)

**Comment by bombadil** [comment]
Let's face the truth, I simply don't have the time to maintain the smcroute package in Debian any longer. I have filed a request for adoption to the Debian bug tracker:
https://bugs.debian.org/906889


If you are interested in keeping the package updated in Debian, feel free to adopt the package. If you are not familiar with Debian's procedures for maintaining packages, feel free to reach out to me. I am more than happy to help with getting you involved.
-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by bombadil** [comment]
The way I got started was by reading up in the [Debian New Maintainers' Guide](https://www.debian.org/doc/manuals/maint-guide/) how to do Debian packaging properly (that was before I even started to think about becoming a DD). Later the [Debian Policy Manual](https://www.debian.org/doc/debian-policy/) will likely become a useful resource. And of course there are plenty of other Debian packaging starters out there in the web (each to his own taste).

Moving forward I would suggest everybody interested in helping to join the [Debian packaging for smcroute project](https://salsa.debian.org/debian/smcroute) on salsa.debian.org and to subscribe to the contact keyword of the smcroute package on the [Debian Package Tracker](https://tracker.debian.org/pkg/smcroute). That way all potential packaging contributors can be reached using the @packages.debian.org alias. @troglobit, If you agree to this suggestion, let me know once you're subscribed, and we can move on from there. Everything else probably just needs to be learned by doing. :smile:

P.S.: I've heard rumors that Debian in the recent years worked on streamlining the NM process (the process that is used to on-board new DDs) to mitigate some bottlenecks. So, I can only recommend at least trying it. That's the only way to find out.

**Comment by troglobit** [comment]
@bombadil Thank you, very kind of you to share your own story! I'll have a look at it this weekend :smiley: :+1:

**Comment by bombadil** [comment]
I just noticed that the New Maintainers' Guide I followed will get replaced soon by the [Guide for Debian Maintainers](https://www.debian.org/doc/devel-manuals#debmake-doc). You might want to read that instead.

**Comment by troglobit** [comment]
@bombadil I'm having a bit of trouble getting an SSO login, but I've got GitLab access at least.

**Comment by bombadil** [comment]
Ok, let's take this discussion offline via private mail.

**Comment by troglobit** [comment]
Update: we're working on it :)

**Comment by bombadil** [comment]
Done.
https://tracker.debian.org/news/986993/accepted-smcroute-242-1-source-into-unstable/
