### ISSUE TITLE
Config file withtout newline at the end of 

### ISSUE THREAD

**Issue by geekmug** [troglobit/smcroute#96]
I suggested using smcroute to a peer, and they ran into an issue today that was difficult to troubleshoot. If you specify a config file like this:
```
$ echo -en "phyint eth0 enable\nphyint eth1 enable\nmroute from eth0 group 224.0.0.0/4 to eth1" > /etc/smcroute.conf
```
Then the `mroute` statement doesn't end in a newline character, which seems to cause smcroute to not add the mroute (`smcroutectl show` is empty), where I would expect to see `(*, 224.0.0.0)`. If I add the newline character at the end of the file, then the `(*, 224.0.0.0)` route shows up.

A cursory glance at the code, it seems like the issue is that `line = fgets(...)` will return a string that doesn't end in a newline and `pop_token(&line)` won't pop a token without a whitespace character after the token. It may not be worth fixing this issue in the parser due to complexity, but it would at least be helpful if `conf_parser(...)` complained loudly that there was an incomplete operation.

**Comment by troglobit** [comment]
Nice catch, thanks!

Fixed in 78666f8.
